### ISSUE TITLE
Pre configure Epichrome Helper and reset as "first open"

### ISSUE THREAD

**Issue by henrikbjorn** [dmarmor/epichrome#105]
I want to use this to distribute an intranet as an application. That requires some configuration of the Epichrome Helper and to reset it (to force the epichome helper to install if needed).

Is there a way to do that? Thanks

**Comment by dmarmor** [comment]
Hi @henrikbjorn,

If I'm understanding what you're trying to do, I don't think there's a way to do it totally automatically. When a user runs an Epichrome app for the first time, it will automatically create a new profile and install the Helper extension. You would then need to import the Helper options you want (which you can export as a json file from your master copy).

Not sure if that helps. Maybe if you give me a little more detail about what your distribution procedure looks like, I could offer more help?

**Comment by henrikbjorn** [comment]
We use it internally for our Support appartment. And creating the app and distribute is easy, however it is a bit of a chore to run around and setup the Helper for 10 people.

**Comment by dmarmor** [comment]
Your best bet might be to set up your master app, run it once and set up the helper the way you want it. Then you could zip up the profile directory and distribute that with the app itself. You'd probably need to write some shell script magic if you wanted to fully automate the process, but it should be simple to have a script copy the app and unzip the profile directory into the right place. That way when the user runs it for the first time, it should be all set up. It won't give them the "just installed" message, but otherwise, it should have all the options you set up.

Would that work for you?

**Comment by henrikbjorn** [comment]
Thanks for the reply, is the Profile located in the  `.app` bundle itself? If so, then it would solve all of my issues. Creating an App locally, set it up and distribute.

**Comment by dmarmor** [comment]
No, the profile is located in each user's Library/Application Support/Epichrome/Apps/<app-ID> folder. If the profile were in the app bundle itself, then multiple users on a system could never use the same app.

For future iterations, I may look into this, but it would be a real change to how Epichrome works, as it would mean that an Epichrome app was really a one-user entity and should be kept in ~/Applications rather than ever being in /Applications.

In any event, it's on my to-do list, so I'll close this for now. Thanks!
