### ISSUE TITLE
Not using any compressed memory

### ISSUE THREAD

**Issue by dzg** [dmarmor/epichrome#107]
Looking at RAM usage ... all the processes belonging to my Epichrome app show 0 compressed memory, whereas my regular Chrome processes do use compressed memory.

This means epichrome is using more RAM than it needs to, doesn't it?

(The selected processes below are Epichrome, all with 0 in compressed mem)

![image](https://cloud.githubusercontent.com/assets/466557/24579329/556a166e-16f3-11e7-99a5-43c451e4005d.png)

**Comment by dmarmor** [comment]
Hi @dzg,

As far as I can tell, memory compression is handled entirely by macOS, and there's nothing Epichrome or any other app can do to enable or disable it. I've done a few little experiments and have noticed that if I quit and restart Chrome, it also shows no memory compression for quite a long time. Is it possible that your Chrome instance has just been open for a lot longer than your Epichrome apps?

Another thought is that generally an Epichrome app will only have one window open, which means it's using much less memory than a Chrome instance with a bunch of tabs open. From what I can tell, macOS automatically decides to compress memory when an app starts to put pressure on available RAM (as a first step before paging). So I imagine if it's not compressing memory for any given process, that's probably because that process is not using too much RAM. And bear in mind that compressing memory may actually be bad for performance, since it's more overhead on the memory access.

I'll close this for now, since I'm not sure what I could do about it in any event, but let me know if you've noticed any performance problems related to Epichrome apps that might be due to lack of memory compression, and I'll reopen.
