### ISSUE TITLE
A way to lock Chrome at specific versions or at least build levels?

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#109]
I've run into scenarios where I want to use various branches at different times... stable sometimes, beta sometimes and even dev sometimes... and occasionally I need an even older version of Chrome.  Has any thought gone into locking Chrome versions in some fashion?  

I have a few ideas, but don't know if this has been considered before.

**Comment by dmarmor** [comment]
Hey @ylluminate, I haven't really looked into this. It would complicate things quite a lot, as presumably these versions would either have different names when the Epichrome apps were created (necessitating some kind of interface to choose which version you want to link to) or else the names would change later, and there'd have to be an interface for relinking).

That said, if it's really important to you to have this, it's possible it could be accomplished with some editing of the config.sh script in Contents/Resources/Scripts of each app, so that it points at the locked version. I don't have time right now to try it out, but if you wanted to mess around with it, I'd be curious.

For now, I'll add it to the wish list. Thanks!
