### ISSUE TITLE
1Password unable to connect to SSBs using NativeMessaging due to code signature

### ISSUE THREAD

**Issue by tamaracks** [dmarmor/epichrome#118]
I know that this may not get resolved because of @dmarmor's other commitments, but I'm just putting it out there in case.

1Password is being updated to use NativeMessaging instead of WebSockets (I guess it's the wave of the future?). It's in the beta now. Unfortunately, this may kill Epichrome for my use. 1Password is unable to connect to the SSBs, unless I disable browser signature checking in 1Password (not recommended).

I had to put 1Password's NativeMessaging json into the SSB app bundle to even make that part work, but because the SSB apps aren't signed themselves, it only works if I leave verifying disabled, which isn't a good long term solution.

Does this mean that Epichrome would have to codesign the SSB's to work with 1Password? Is that even technically possible?

**Comment by henderea** [comment]
Yes, it is *technically* possible to codesign on a client machine.  It might require the users to install xcode and its tools, but it *should* be "possible".  However, that would require including a code signing cert with the app bundle, which is a huge security issue since it would let anyone sign as that person.  It could technically be encrypted with a decryption key in the code, but with this being an open-source project, that decryption key would still be in plain sight, leaving the code signing cert vulnerable.

In order to allow for code signing of the apps from an open source app, the only real way to do it is to require users to provide their own code signing cert.  I personally have *my* own since I do some mac development, but most users will not have one.

Theoretically, if you have a server running macOS, you could do automated signing as a service, but there are plenty of issues with a general signing service, and providing a Epichrome app *generator* on the web would still have the issue of invalidating the code signature when you update chrome or Epichrome.  Not to mention that the owner of this server would have to cover server hosting and bandwidth costs, and I don't think mac servers are as cheap as linux ones.

I think the only real option for providing signing is to add in the ability to specify a code signing cert in the setup and upgrade processes, but each user would basically have to have their own, and I don't think you can legally get one without having a $99/year apple developer account.

---

Outside of things like that, it would take a rewrite of Epichrome to implement anything that would avoid the need for code signing, and I don't have any ideas other than the plan the dev has to eventually make it a chrome extension (assuming that even solves the issue).

If you want to pay $99/year (plus tax) for an apple developer account, or already have one, I could help walk you though the setup process and code signing, but that isn't a general solution, and it makes using Epichrome no longer free.  You could try finding a code signing cert on the web for free, but I would assume that doing so would be against the terms of use for the apple developer program, and you would have no way of knowing if the file is safe, and apple might invalidate the cert.

---

If anyone has any other ideas, I might be willing to give implementing them a shot at some point, but I won't guarantee any timeline or even an implementation, since this isn't really my project, and I personally don't mind disabling code signing checks in 1Password.

**Comment by dmarmor** [comment]
Hey @tamaracks & @henderea -- this is very bad news for me as I use 1Password heavily in my own Epichrome apps. If I can find some time I'll try the beta extension and see what's going on, but I suspect as @henderea pointed out it will not be feasible to solve this (I think even turning Epichrome into an extension won't, since the SSBs themselves have to be app bundles).

But I'll keep an eye on it and see if I can find any good workarounds. Otherwise, for myself I'll probably just turn off the code-signing and trust that I'm not getting weird fake versions of Chrome on my system...

**Comment by dmarmor** [comment]
Hi again @tamaracks --

I just switched the 1Password extension from the release to the beta version in one of my Epichrome apps, and it appears to still be working just fine. Do I need to do something else to see the problem you're experiencing?

Thanks!

**Comment by henderea** [comment]
After updating 1Password to 6.8, I also started having trouble re-auth'ing it with my Epichrome SSBs.  It was saying it was unable to connect and offered buttons "Get Help" and "I'll restart my browser".

I eventually figured out that I could fix this by unlocking 1Password and relaunching the SSB.  It only seems to have this issue when the main 1Password app is locked.  Likely a bug in 1Password, rather than an issue with the SSB.

As a note, I already had browser signature checking off, and that setting was kept.  Not sure if it would have issues if I re-enabled that.

**Comment by dmarmor** [comment]
Hi @henderea --

Thanks for this report. I just updated to 1Password 6.8 and tested it out and sure enough, it won't work in my Epichrome apps. However, I was able to copy the native messaging .json file from my Chrome profile into my Epichrome app's profile and then it worked perfectly (even with browser signature-checking on, by the way).

I'll add code for the next version so that on startup, apps will attempts to link any native messaging .json files in a user's Chrome profile into their Epichrome app profiles. This isn't a perfect solution as people may have multiple profiles in Chrome, etc., but I think it should solve the problem in the vast majority of cases.

**Comment by henderea** [comment]
Actually, I didn't have to copy anything.  I just had to unlock 1Password and relaunch the SSB, and it successfully ran the re-auth process.  I think you just need to make sure 1Password is unlocked, and it's probably a 1Password bug.

**Comment by dmarmor** [comment]
Just did a bit more testing. It seems to be the case that if browser signature verification is turned off, then the .json file is not needed (it's possible that in that case 1Password reverts to its old style of browser communication). But if I get rid of the .json file and turn browser signature verification back on, then I endlessly get the "can't communicate" message.

It seems worth it to at least try to make Epichrome apps able to communicate with native messaging the same way Chrome does and not force 1Password users to lower their security in order to use them...

**Comment by tamaracks** [comment]
Yes, I can verify that I have been told by 1P people that the JSON isn't needed if that verify setting is off. I am pretty sure that in that case 1P resorts to the old way of communicating with the browser. It does allow Epichrome apps to work, but obviously that setting isn't recommended by 1P, as it lessens the security to some degree. 

It saw your request for me to try again, but I haven't had much chance to sit down with my laptop to do so. At the time I first ran into this issue, I did try experimenting with copying the JSON file from Chrome into the various SSB support files in what I think was the right location and didn't have success, but it's possible that something could have been updated in that time or I was doing it wrong. I'll try to sit down with it and test again soon.

**Comment by dmarmor** [comment]
I've just uploaded Epichrome 2.1.20. Give it a whirl and let me know how it works for you. For me, I've had no issues with 1Password 6.8 with "verify browser signature" turned on, presumably using native messaging. I've tested it with both the current release version of the 1Password extension and the latest beta.

I'll close the issue for now, but if you find any problems, let me know and we can reopen. Thanks!
