### ISSUE TITLE
With epichrome 2.1.18, epichrome apps can't be focused using Hammerspoon

### ISSUE THREAD

**Issue by philc** [dmarmor/epichrome#123]
In short, [Hammerspoon](http://www.hammerspoon.org/) has a function called `hs.application.launchOrFocus` which focuses an app that's open. This suddenly stopped working with Epichrome apps after the latest Epichrome update.

I'm not sure if you know why this is or care to repro it, but I thought I'd at least document a workaround so Google can find it. Here is a replacement for `hs.application.launchOrFocus` which can be used by Hammerspoon users in their init.lua:

```lua
-- Like hs.application.launchOrFocus, except that it works for apps created using Epichrome.
-- I'm not sure why this implementation has different behavior than hs.application.launchOrFocus.
-- Reference: https://github.com/Hammerspoon/hammerspoon/issues/304
function myLaunchOrFocus(appName)
   local app = hs.appfinder.appFromName(appName)
   if app == nil then
      hs.application.launchOrFocus(appName)
   else
      windows = app:allWindows()
      if windows[1] then
         windows[1]:focus()
      end
   end
end

-- Here, "Gmail" is an app created with Epichrome.
hs.hotkey.bind({"cmd", "ctrl"}, 'U', function() myLaunchOrFocus('Gmail') end)
```

**Comment by dmarmor** [comment]
Thanks for the workaround, @philc. I have a slight suspicion this problem might be related to similar problems @ylluminate is reporting. I might try something and put up a beta for you guys to try and see if it solves any of these issues. Stay tuned...

**Comment by dmarmor** [comment]
Hey @philc -- not at all sure if this will help, but I just rolled back one change I made to the Chrome engine. If you have a chance, would you try this and see if it helps? (Back up your apps and Epichrome 2.1.18 first so you can roll back if you need to.)

https://www.dropbox.com/s/srvu6zz0o9mm2st/Epichrome.app.zip?dl=1

**Comment by rschend** [comment]
Hey @dmarmor , been awhile since I poked my head in here and contributed to the troubleshooting, but still loving Epichrome...

If you recall, the issue I filed was about compatibility with BrowserFairy. I've since moved to Choosy, as it's more polished, but it's been working great with Epichrome. 

But 2.1.18 broke it. My Epichrome browsers just ignore links sent to them from Choosy altogether. Native Chrome still responds to them fine.

2.1.19 seems to have fixed it...the SSBs are now catching links. But OSX isn't changing focus to the target SSB like it (usually) did before. I don't know if that's something you can affect.

Cheers.

**Comment by rschend** [comment]
Whoops...I take that back...

Focus seems to be working as it was before. Which wasn't/isn't 100% consistent. Some clicks just inexplicably don't cause the SSB to gain focus, even though it loads the link just fine.

So, I'm betting .19 has fully corrected the issue that .18 introduced. The focus issue might not be related to Epichrome at all?

**Comment by dmarmor** [comment]
Yeah, I'm not sure about that focus problem, but I suspect it's either a macOS problem or might have to do with Choosy? I guess I'll close this issue for now, since I can't think of any way to help with the focus problem that would be within the scope of Epichrome. But if you notice any patterns or have any ideas that seem like there might be something going on with Epichrome, let me know and we can reopen. Thanks!

**Comment by talleux** [comment]
Hello, i have the same problem using choosy: if an epichrome browser is already open, choosy won't focus on it nor send the URL - simply nothing happens. If i choose another browser (tested with Firefox, Safari, Chromium, Chrome Canary, Opera) then it works perfectly.
I use the current latest epichrome 2.2.3, and OSX El Capitan.

I really love epichrome, especially combined with choosy. It has become a central productivity tool in my daily work. What could i do to find a workaround or help finding a solution?
