### ISSUE TITLE
Epichrome extension won't work in regular Chrome

### ISSUE THREAD

**Issue by dsemaya** [dmarmor/epichrome#130]
I tried loading the Epichrome extension into my main copy of Chrome so that I can force it to open links in my default browser.  My default browser is [Choosy](https://www.choosyosx.com), not Chrome, and I use it to direct links to various Epichrome apps.  

The extension shows me the following error:
> **Not connected to extension**
> Try disabling and re-enabling the extension. If it still doesn't work, you can check for updates/fixes, or open an issue at the project's github page.
> 

Can it be possible to run the extension this way?

**Comment by dmarmor** [comment]
Epichrome Helper is not meant to run under Chrome and will definitely not work except in an Epichrome app. If you really need it in a general Chrome browser, the best way to do that would be to create an Epichrome app with a tabbed-window interface (rather than app-style) and *no* URLs specified. That will create a browser that should obey your homepage settings just as Chrome would.
