### ISSUE TITLE
Apps created on High Sierra duplicate launch when opened

### ISSUE THREAD

**Issue by mhuusko5** [dmarmor/epichrome#133]
I've encountered a strange issue where when I try to open an already opened epichrome app, instead of activating/bringing it to focus, a duplicate app opens, then immediately closes but with the tab(s) from the duplicate app transferred to the open app.
I'm not sure the reason – only that it's only happening with epichrome apps I've created since updating to macOS 10.13.

**Comment by mhuusko5** [comment]
It stopped happening, then started again. Also assigned space is not being respected, instead app is launching/creating new windows in the space chrome is assigned to.

**Comment by thebai** [comment]
this is happening to me also. Tried recreating the app with a number of different settings to no avail.

has anyone found any fixes?

**Comment by bfenster** [comment]
I can add that this does not seem to be limited to applications created on High Sierra. Some (but not all) of my epichrome applications created pre-10.13 has the same problem.

I've experimented with various settings to try to fix this and I'm not certain what's actually helped, but I think checking the "Send incoming links to the main window instead of a new tab" option in the Epichrome Helper extension settings within the app (and then restarting the app) is a fix.

**Comment by dmarmor** [comment]
I'll look into this. The behavior I see on my system is a little different. When I launch an already-open app, nothing at all happens. It appears to launch and then immediately quit, leaving the running version unchanged but also not bringing to the front.

In my experience, the expected behavior with other apps is that launching it when it's open would simple bring it to the front. Is that what you guys are expecting/hoping when you launch an already open Epichrome app?

**Comment by jurb** [comment]
> I'll look into this. The behavior I see on my system is a little different. When I launch an already-open app, nothing at all happens. It appears to launch and then immediately quit, leaving the running version unchanged but also not bringing to the front.
> 
> In my experience, the expected behavior with other apps is that launching it when it's open would simple bring it to the front. Is that what you guys are expecting/hoping when you launch an already open Epichrome app?

@dmarmor This is exactly what I'm experiencing and hoping can be fixed!

**Comment by dmarmor** [comment]
Hi all,

I wanted to let you know I'm working on a fairly major update that I believe will solve this, as well as many other long-standing problems. With my work schedule, it may take a while, but I'll let you know when it's ready for testing. Thanks for your patience!

One more thing:

#### <shameless_plug>
#### I've set up a [Patreon](https://www.patreon.com/epichrome). If you find Epichrome useful and would like to help support its continued development, I've love it if you considered joining. Your membership would help cover the costs and time I put into the project. Membership is per-release, so you'd only be charged when I put out a new version with significant work in it (e.g., assuming I end up with the bundled-Chromium architecture, I would not consider bumping the Chromium build to be a new version).
#### </shameless_plug>

**Comment by dmarmor** [comment]
Hi all! I believe this issue should be solved in 2.3.0, so I'll close it for now. If you notice this problem in the latest update, please let me know and I'll reopen.
