### ISSUE TITLE
IF Pinned tabs THEN Epichrome will reload them.

### ISSUE THREAD

**Issue by pattulus** [dmarmor/epichrome#15]
It's not really a bug and there's also a relatively simple workaround, but anyway… here's what is happening: if you have added a tab, pinned it and restart your SBB, then the pinned tab will load along with all other specified tabs – even the pinned one if it's specified. 

I often use SBB's for project based work. So in this example I have our YouTube channel, FeedPress, the server-side BitTorrent Sync and Google Analytics pinned. The rest of the tabs are our projects main Trello boards:

![ssb-example](https://cloud.githubusercontent.com/assets/591759/8750774/aee707f0-2ca9-11e5-9a0c-4200636392f7.jpg)

If I restart this SBB it will reload this setup and add all the four pinned tabs (since they were initially specified in the setup and hence added "fix" to the SBB).

A workaround for this example would be to only setup the Trello boards and then manually open the other/pinned tabs in the read-made SBB.

**Comment by dmarmor** [comment]
Hi Patrick,

I just reproduced this behavior on my system. I wasn't really familiar with pinned tabs, having never used them myself. It might be possible to modify the behavior of the SSB (using the Helper extension) to close pinned tabs on startup or something, but it wasn't clear to me that that would always be desirable behavior.

It seems that probably the workaround you described at the end of your post is the most robust solution: when you create the SSB, only specify the tabs you *don't* want pinned, and then open and pin any others when you first run it. It seems like that would let users create any setup they want, right?

If there's any different behavior or options regarding pinned tabs that you think would be better than that solution, please let me know and I can try to work them into the system. Otherwise, I'll probably close the issue and leave it as is.

Thanks for the report!

**Comment by pattulus** [comment]
I think the workaround is flexible enough to handle a lot of what users want out of a SBB.

If there's ever a way to edit existing SBB's without deleting and recreating them, for instance in an extension then it would be cool to have the possibility to mark certain tabs as pinned by default. But since everything works this is not really a pressing matter. ^__^

**Comment by dmarmor** [comment]
Sounds good. I'll close the issue for now, but add this to my to-do list for the extension version of Epichrome. Thanks for the feedback!
