### ISSUE TITLE
Multiple Chrome Personas Support

### ISSUE THREAD

**Issue by ey51** [dmarmor/epichrome#150]
This is awesome.
Not having webapps as separate windows that I can task switch from/to was a major pain for me on mac (moving from win), and you elegantly solved it. The rules in the options are also great. Thank you. I can even donate to your paypal.
I have one suggestion: I use two personas in chrome (one personal and one for work). I have also made two docked apps using your tool for personal gmail and work gmail. I would have liked to be able to define that links from the work gmail open in the default browser using the work persona, and from the private gmail in the private persona (rather than just using the default browser and letting it do what it wants, because now, it seems it's arbitrary where the link opens (in which persona's chrome).
If it isn't clear, I can elaborate (serial+github at google mail dot com)

**Comment by dmarmor** [comment]
Hi @ey51, sorry for the slow reply, and I'm very glad you're getting use out of Epichrome.

If I understand what you're asking, then I'm not sure I can solve it, because I don't know of a way to direct Chrome to switch personas via link. All that the Epichrome extension is really capable of is directing links either to its host instance of Chrome or to the default system browser. It doesn't have any way to control that browser. I've done a little searching and it actually doesn't appear to be possible to programmatically switch profiles on a running Chrome instance. This seems to be something you have to do manually as a user.

So unless I've misunderstood what you're asking, it doesn't look like I'll be able to solve this one for you. If I haven't gotten it right, please let me know and I can write you offline to get more detail.

**Comment by ey51** [comment]
Okay. Gotcha and thanks.
