### ISSUE TITLE
Run the window as an existing user

### ISSUE THREAD

**Issue by kotekhutsishvili** [dmarmor/epichrome#151]
Can it be launched under the user which is already running on Chrome? Because I use some extensions and if I login there again I have basically two chromes running on the machine.

**Comment by dmarmor** [comment]
Hi @kotekhutsishvili, I'm not sure I understand your question fully. Are you trying to have Epichrome apps share a profile with your main Chrome profile? That is not possible, as Epichrome apps are hardwired to have their own profiles.

However, in the Chrome settings you can set it up to sync any of your settings between different instances. I use this myself so that when I create a new Epichrome app, the first thing I usually do is sign into Google in the app, turn on sync and let it sync all my usual extensions. Then I turn sync off again so I can customize which extensions and such I want on the Epichrome app without messing up my main Chrome profile.

I hope that helps? If I've misunderstood your question, please give me some more detail so I can better understand. Thanks!

**Comment by dmarmor** [comment]
Just checking in once more, @kotekhutsishvili. I'm going to close this issue for now, but if you have any more info that can help me understand the problem, please let me know and I'll reopen.
