### ISSUE TITLE
RescueTime extension doesn't log web use in SSB

### ISSUE THREAD

**Issue by kranix0** [dmarmor/epichrome#165]
I'm an avid user of [RescueTime](https://www.rescuetime.com) as a means of measuring and managing my time use. With normal Chrome, the RescueTime browser extension is able to track what sites I'm looking at. In an Epichrome SSB, the extension itself appears to know what I'm looking at (see image below) but this isn't reported in my RescueTime account. Instead, it just reports the whole SSB app (probably via the RescueTime desktop app, not the browser extension) and not actual sites.

![image](https://user-images.githubusercontent.com/461278/45910905-81414680-be50-11e8-8628-c60561d4a1ec.png)

**Comment by dmarmor** [comment]
Hi @kranix0. Sorry for the very slow reply on this. I can't think what would be causing RescueTime to fail to track sites in an Epichrome app, as they are nothing more than instances of Chrome. I wonder if the desktop app is somehow superseding what the extension is doing, since it doesn't recognize the Epichrome app as a browser? Is it possible to tell the desktop app to ignore certain apps?

Another possibility might be that RescueTime doesn't expect you to have multiple instances of Chrome running the extension, and so the extensions communications with the server or desktop app (I really don't know how RescueTime works) are getting stomped on by the extension in your main Chrome.

Do any of those sound like possibilities? If one of those ideas doesn't help, there's likely not much I can do.

**Comment by kranix0** [comment]
Thanks for the reply. I've moved away from Mac so I'm no longer using Epichrome. I suppose you can close this issue, unless there are other people who want to see it fixed.

**Comment by dmarmor** [comment]
Got it, thanks for the update. I'll close for now.
