### ISSUE TITLE
[Browser] wants access to control Finder

### ISSUE THREAD

**Issue by iandundas** [dmarmor/epichrome#170]
Since upgrading to Mojave, I now get this message whenever opening one of my Epichrome-powered browsers. (I do not get it when opening vanilla Chrome, however).

<img src=https://dsc.cloud/iandundas/Screen-Shot-2018-10-12-10-37-17.10.png />

<img src=https://dsc.cloud/iandundas/Screen-Shot-2018-10-12-10-39-57.15.png />

I'm not keen to say "OK" without knowing why it needs this permission(it also asks it again the next day, no matter what the answer given is).

**Comment by afsoltys** [comment]
Same problem! @iandundas any luck? Anyone?

**Comment by dmarmor** [comment]
So this dialog box is part of Mojave's new security settings, and I believe it comes up either because when Epichrome apps launch they need to update themselves (to link to Chrome, update their config and such). Or it might have to do with their use of AppleScript to display dialogue boxes.

In any case, it should *not* ask for this permission on every launch. Once you've given permission, it should just work on the next launch. It's possible the extra code-signing that Epichrome apps now have since 2.2.4 will help with this. Can you let me know if you're still experiencing this problem?

**Comment by dmarmor** [comment]
Closing this issue. If anyone is having trouble with these permission windows opening repeatedly, please let me know and I'll reopen.
