### ISSUE TITLE
Question about making epichrome a Chrome extension

### ISSUE THREAD

**Issue by jameschao** [dmarmor/epichrome#172]
> Change Epichrome.app from a standalone app to a Chrome extension.

@dmarmor, can you explain a bit more about why you think that would be a good direction to go? Is it more for ease of use (e.g., turn the active tab into an SSB) or is it more for a technical reason?

**Comment by dmarmor** [comment]
Hey @jameschao, there are several reasons I want to go the extension direction, mostly to do with ease of use and interface. Right now Epichrome is a series of AppleScript dialogue boxes, which is a pretty terrible UI. I figure since anybody using Epichrome must have Chrome installed, why not leverage that UI? It also would allow a bunch of other cool enhancements. If you invoked the extension, it could autofill the URL for the frontmost tab as the app URL (or all the tabs in the window if creating a tabbed app). It could also grab the web page's favicon and present that as a default icon.

It would also help with what I eventually want to do, which is to allow apps to be edited after they're created. The runtime extension would ideally have a page separate from the link-routing rules where users could edit the app's URLs, window style, name, and icon, and on next reboot the changes would take effect.

All that said, I don't know when or if I'll ever have time to do what would amount to a major rewrite of the entire system...
