### ISSUE TITLE
How to rename an Epichrome app?

### ISSUE THREAD

**Issue by ylluminarious** [dmarmor/epichrome#180]
I would like to completely rename an Epichrome app. I could just rename the relevant folders, but it appears that I also need to edit files such as `Info.plist`. There are apparently many such files that may need to be edited to the new name, as revealed by `grep`. I do not want to leave any loose ends which could mess up my app. Is there any straightforward (or at least thorough) method to completely rename an Epichrome app?

**Comment by dmarmor** [comment]
Hi @ylluminarious,

I don't exactly recommend the following method as it's kind of kludgy, but it should work, with the warning that it involves mucking around in the app bundle, so there's always a chance something will go wrong and render the app unusable. Definitely recommend backing up the bundle before trying it. With that caveat, here's how you'd change OldName.app to NewName.app:

1. Make sure OldName.app is not running.
2. Edit OldName.app/Contents/Resources/Scripts/config.sh. You'll need to find the following lines and change the name in each:
```bash
CFBundleDisplayName=OldApp
CFBundleName=OldApp
SSBChromeEngine=OldApp.app
```
3. Delete the Payload directory:
```bash
rm -rf OldName.app/Contents/Resources/Payload
```
4. Rename the app bundle from OldName.app to NewName.app.

Next time you launch, it should rebuild the payload and you should see NewName both in the dock and the menu bar.

Closing this issue for now, but if you run into problems with this, let me know and we'll reopen.

**Comment by ylluminarious** [comment]
@dmarmor Thanks so much! Everything seemed to go without a hitch and my app has been renamed in both the dock and menubar.

I am curious about a few points, though. I noticed that you left `CFBundleIdentifier` and `SSBProfilePath` alone in `config.sh`. These variables still have the old app name in them. Is this on purpose? I'm also wondering whether I should rename my app's profile folder or just leave it alone.

**Comment by dmarmor** [comment]
There's no real reason to change the identifier or profile path. I didn't include it in the process above as the app will function just fine as it is. But if you do want your identifier and profile path to match the new app name, here's how you'd do that (again using OldName & NewName as examples):

0. **Please be extra cautious trying this, and back up both your app and your profile directory before starting. I have not had time to test this process myself.**

1. Make sure the app is not running.

2. Make sure that no other app on your system has the new identifier you want, by making sure the following command does not return an app path:
```bash
mdfind "kMDItemCFBundleIdentifier == 'org.epichrome.app.NewName'"
```

3. Again edit OldName.app/Contents/Resources/Scripts/config.sh, and this time change the following lines:
```bash
CFBundleIdentifier=org.epichrome.app.NewName
SSBProfilePath=Library/Application\ Support/Epichrome/Apps/NewName
```
(This is assuming that your library path is the standard one. Basically you should just change OldName to NewName at the end of whatever the path is.)

4. Rename your profile directory to match what you just changed it to in the SSBProfilePath line of config.sh.

When you launch your app, it should open as expected, using the updated ID and profile path.

**Comment by ylluminate** [comment]
I guess the followup to this is: how do you also change the icon for the app properly?  Simply setting in Finder seems to only be active in Finder and when you start the app it overwrites it again.

**Comment by ylluminarious** [comment]
@ylluminate [I use these instructions](https://github.com/dmarmor/epichrome/issues/47#issuecomment-173814881) to change app icons. It's not exactly "proper" and it's not ideal, but it works. It's a good idea to backup the app bundle before following that procedure, though.

**Comment by ylluminate** [comment]
So @ylluminarious I see something here that we should issue a PR on.  I thought I'd mention it in this ticket since it has something to do with a point above, but it is ultimately a different issue.  

While @dmarmor does indeed set the `CFBundleIdentifier` within the `SSB.app/Contents/Resources/Scripts/config.sh`, it is NOT set within the necessary `SSB.app/Contents/Resources/ChromeEngine/SSB.app/Contents/Info.plist` - retaining:
```
<key>CFBundleIdentifier</key>
<string>com.google.Chrome</string>
```

I'm not sure what the "right" way to do this would be, but I assume that we should programmatically change this with a script (perhaps each time?)...

The reason that this is important is that it causes some various problems with different apps - one such app being `App Tamer.app` in that it can't identify each Epichrome instance as a separate app and so it will end up modifying ALL of them.  This is really troublesome sometimes when I want to perform different processes on different Epichrome instances going in the background and may be taking up too much processor time or memory, etc.

**Comment by dmarmor** [comment]
I actually used to change the bundle ID in the engine, but had to stop doing that during one of the Chrome or macOS updates, because it broke Chrome's code-signing and caused all sorts of problems. At present, I don't have a good solution to that, which also causes other problems (I think it's what underlies the Applescript and Keyboard Maestro problems various folks are having). So yeah, I wish I could assign each running instance its own bundle ID, but at present I don't think that's possible.

**Comment by ylluminarious** [comment]
@dmarmor Is this process any different for the new betas based on Brave Browser?

**Comment by dmarmor** [comment]
Well, the process is different for Chrome-based beta apps, as config.sh no longer holds the relevant info. For Brave-based apps, renaming an app basically can't be done at the moment, as the localization strings (which control what you actually see when the app is running) are pre-filtered when the app is created.

I am planning to make it possible to edit apps at some point hopefully in the not-too-distant future after the 2.3.0 release, so if you're using Brave-based apps, the best bet is to wait for that update.

**Comment by ylluminarious** [comment]
@dmarmor Sounds good, I'll hold off till then. Thanks!

**Comment by ylluminarious** [comment]
@dmarmor Now that the 2.3.0 release is out, is this possible yet?

**Comment by dmarmor** [comment]
It's the next major feature on my agenda, but after spending way too much time on Epichrome over the last few months, I am having to slow down my work on it quite a bit, so this won't be happening imminently. But it's top of my list and I will be working on it whenever I have time!

**Comment by ylluminarious** [comment]
@dmarmor Ok, I understand. Looking forward to it! 😃
