### ISSUE TITLE
Kill all Chrome instances?

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#185]
Hey @dmarmor do you have a quick way to kill all Epichrome Chrome instances as well as Google Chrome proper in one fell shell command?  I'm having a devil of a time here and need a quick way to just nuke all Chrome processes fast sometimes...

**Comment by ylluminate** [comment]
Thinking about this further, I guess it would be useful further to print out a list of all Epichrome / Chrome instances running currently and then throw their pids into `kill -9`.  That way one would have a list of all instances before murdering them all.

**Comment by dmarmor** [comment]
I threw together a little script to try to handle this for you: **[killepichrome](https://www.dropbox.com/s/zu77dtxexnhp4ei/killepichrome?dl=0)**. It's pretty rough, so not terribly user-friendly, but if you put the attached file in your path and chmod it executable, it should help. The usage is like this:

```
killepichrome [<app> ...]
```

If you don't pass any app names, it will kill _all_ running Epichrome apps (outputting a message for each one so you know what's being killed). If you do pass app names, it will only kill those apps (and warn about any you passed that were not running).

Because I did it so quickly, it's kind of particular about the app names. They must match exactly (case-sensitive) and must _not_ have .app at the end. So a sample run might look like this:

```
killepichrome Gmail 'Google Calendar' 'Google Drive'
```

and the output might look like this:

```
Killing Gmail [77361]
Killing Google Calendar [89042]
Warning: Google Drive not running
```

Closing this issue for now. If you have any trouble with this or find bugs in the script, please let me know.

**Comment by ylluminate** [comment]
Wow, nice.  Better than the nuclear script I threw together - but perhaps they can be used together.  I'll have to go through yours more carefully and put some makeup and a wig on mine to not let it be so ugly so you can take a peek at it (and hopefully not scream too loudly from the jump-scare).

**Comment by dmarmor** [comment]
Running killepichrome with no arguments should function as you're describing, and should kill all running Epichrome apps. And hmm, it should definitely _not_ kill Chrome proper, as it's searching specifically for instances of Chrome run through the ChromeEngine directory.

Can you try this again and confirm that it's killing Chrome proper?

**Comment by ylluminate** [comment]
So I finally had a chance to test this out (crazy last several days - apologies). It does not kill Chrome, but it also is not killing `Epichrome` instances either.  When I executed it to kill all `Epichrome` instances it resulted in:
```
Error: unexpected ps output:
 3052 ??         6:13.57 /Applications/EPICHROME_APP_NAME.app/Contents/Resources/ChromeEngine/EPICHROME_APP_NAME.app/Contents/MacOS/Google Chrome --user-data-dir=/Volumes/alma_usr/Users/USERNAME/Library/Application Support/Epichrome/Apps/EPICHROME_APP_NAME
```
(Where EPICHROME_APP_NAME is the actual Epichrome app name)

**Comment by dmarmor** [comment]
Might've made my regular expression a little too restrictive. Try **[this](https://www.dropbox.com/s/f4vksr2s2u84pel/killepichrome?dl=0)** update.
