### ISSUE TITLE
Rename "Google Chrome Helper" processes to "Epichrome Helper"

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#187]
@dmarmor I've been having some trouble with having so many "Google Chrome Helper" instances. Apple is telling me that Chrome is the culprit for system hangs and various trouble I've been having due to how Chrome works with having so many processes, etc.  I've been needing to kill it all at once perhaps once or twice a day, but there's no easy way to do it.

From what I'm seeing here it would be a good idea to rename "Google Chrome Helper" to "Epichrome Helper" or some other name like Electron apps do. Do you have any ideas on how this could be readily done?  By doing this I could isolate killing all parent processes for all "Epichrome Helper" instances to then see if this could resolve some of this headache I'm having - while also leaving Google Chrome proper running...

**Comment by dmarmor** [comment]
Closing this issue, I think we have the best solution we can with either your script or the one in issue #185.

**Comment by ylluminate** [comment]
Perhaps so.  Having the unique names would be helpful though in determining troubled Epichrome instances and perhaps even what might be causing more specific problems in a certain site.  But we can live with it.  I was hoping there was a way to do this as per Electron to make things "cleaner."

**Comment by dmarmor** [comment]
Yeah, unfortunately I can't really do anything about the name of the helper processes, since I basically can't make _any_ changes to Chrome when I embed it inside running Epichrome apps. Under Mojave, any change at all to Chrome causes all kinds of Gatekeeper problems and makes the apps not function well. Presumably this will only get worse going forward as Apple clamps down on app security. I'm a little worried that in the future even changing the icon will stop working, and then goodbye custom Epichrome icons...
