### ISSUE TITLE
2.3.0-beta: Firewall asks if I want to allow incoming connections on EVERY launch with chromium browser

### ISSUE THREAD

**Issue by henderea** [dmarmor/epichrome#195]
My main computer is owned by the company I work for, and among the various settings they force upon me is enabling the mac system firewall.  It seems that **every** time I launch my browser (converted to chromium), it asks me if I want to allow it to accept incoming network connections, even though I click "allow" every time.  I checked my firewall list, and it has the path `/Users/erichenderson/Library/Application Support/Epichrome/Apps/ScrumStuff/Engine.noindex/Scrum Stuff.app` listed as allowed.

As a note, because the company settings don't allow me to manage the firewall through system preferences, I use the command-line interface for managing the firewall.  The specific command I use to check what is configured is `/usr/libexec/ApplicationFirewall/socketfilterfw --listapps`

A snippet from the output of the firewall list command:
```
76 :  /Users/erichenderson/Library/Application Support/Epichrome/Apps/ScrumStuff/Engine.noindex/Scrum Stuff.app
 	 ( Allow incoming connections )
```

**Comment by dmarmor** [comment]
I don't have much experience with this kind of firewall issue, but the first thing I'd recommend is to also add the main app to your firewall list. It seems possible to me that the firewall is reacting to that app and not the engine.

Please let me know if that fixes it, and if not I'll try to think what else it could be...

**Comment by henderea** [comment]
It did not fix it.  On Patreon, you indicated that the engine app gets replaced with the actual engine on startup, so maybe the fact it gets replaced every time is the issue.

On another note, I had my computer freeze and was forced to perform a hard shutdown while I had one of the Chromium apps open.  I ended up discovering that it had lost all of my info when I started it back up from the engine app.  After quitting and launching from the app in `/Applications`, it brought back my original setup.

Unless I just wasn't paying attention, when I started up the chromium app that _hadn't_ done the replacing, I didn't see the firewall warning.  That is part of why I suspect that replacing the engine with the chromium instance is the reason I keep getting asked for confirmation.

As a note, the actual Chrome browser does not need firewall access.  The firewall is only for incoming connections, so if the browser doesn't host any sort of network server process, it shouldn't normally give me the firewall prompt.  If you have it running a server to manage the special behavior, I would recommend switching to a **Unix** Socket server instead of TCP if possible.  I don't think a Unix Socket server will interact with the firewall, and using a Unix Socket means it communicates without taking up a network port and can only be accessed via the local filesystem (meaning no possibility for a security risk).

**Comment by dmarmor** [comment]
Hmm. That is very puzzling. Regarding the firewall, I can't think of anything in the main app that would trigger it. The only time the main app uses TCP is once a week when it checks GitHub to see if there's a new version of Epichrome. And that's outgoing, so shouldn't trigger the firewall.

The only thing the main app leaves running is a tiny helper app that does nothing but sit and wait for the engine to quit, then cleans it up. It doesn't talk to the internet at all, and doesn't use any TCP communications even locally.

So I'm at a loss here. Given that it appears the firewall is basing its rules on the path to the engine app, and that doesn't change when the engine is activated and deactivated, it doesn't seem likely that's the problem. And in any case, neither the activated engine nor the placeholder should be triggering it.

If you have any other ideas, I'm happy to try adding some logging or something to the next beta to try and help diagnose it.

Regarding the computer freeze, I hope that wasn't related to Epichrome. It shouldn't be, given that all that was running at that time would've been an instance of Chromium.

As for losing the app info, what happened there was that when the computer froze, the helper died too and thus didn't clean up the engine. So when you restarted and tried to launch from the engine app, you were not launching the placeholder, but the live engine, which is nothing but an instance of Chromium. So it just launched a generic Chromium instance which is why it looked like you lost your info. You did the right thing by launching from the main app. Once you quit that run, the helper would've brought back the placeholder to the engine app.

**Comment by dmarmor** [comment]
I had one possible thought, though it doesn't seem likely. I wonder if you've checked to see if the engine app is in the socketfilterfw --listapps listing both when the app is running and when it's not? Given that the engine app is being altered when it's not running, maybe the firewall is noticing that and removing it from the list, and thus triggering it to ask for permission again the next time it runs?

**Comment by dmarmor** [comment]
Hey @henderea, just checking up on some old issues. I'm closing this for now, but if you're still experiencing this and/or have any more info that could help track it down, let me know and I'll reopen.
