### ISSUE TITLE
Volume Differences & Pain

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#201]
Well, I've been thinking a lot about the situation with keeping Chrome and Chromium in my ~/Applications folder.

I've tried the Chrome in ~/Applications for a couple days and I have to say that I'm really unhappy with one thing: I can't use 1Password.  This is simply a sacrifice that I can't make with the work that I do in enough cases that it really makes work more painful.

I can leave 1PW out of about 90% of my Epichrome apps, but then there are those 10% that are really, really painful.

I'm not entirely sure what to do.  

Up to now (<=2.2x) I've been operating Chrome and Epichrome in `/Applications` with Epichrome apps residing there as well and then `~` being on a different volume.  Now with the new understanding, I'm trying to grapple with this pretty hard... and I have to say that I'm still no better off or settled than I was at the start.

Is there something else we can do in this situation to give more flexibility to Chrom* & Epichrome to work in situations where we have non-same root volumes for the user accounts?

**Comment by dmarmor** [comment]
I have a possible fix for this (and also a problem @henderea is having with 1Password with the Chrome engine. It's pretty ugly, though. Basically the way it would work is this: when you install Epichrome, it would get installed in a subfolder of /Applications and create an Engines folder alongside itself there. Then that folder would have to have subfolders for each user, and those would have subfolders for each app, and the engines would be created inside those. It feels pretty kludgy to me to be mucking around in /Applications like that but I can't think of another way to both fix 1Password for Chrome under Catalina and solve your problem.

I guess my main question for you here is, would that actually work for you? I'm not sure I know all the ins and outs of your setup, so want to make sure I don't go down the road on a solution that won't work for all users.

**Comment by ylluminate** [comment]
I really don't care where things live as long as I can isolate my drives such that OS is on one volume and my user directory can live on another volume.  Personally I think perhaps keeping Epichrome and all of its children closely associated could be better. 

While I'm saying this, I guess ultimately I'm not really particular about where the settings live either as long as all of this is simply clear.

As per the last ticket I replied to: My biggest pain point and concern now is trying to get all of my Epichrome apps to show up in Browser Fairy again right now. I guess I need to research how apps get registered / recognized by macOS such that they show up in the proper places and how to kind of list these things at the shell level in order to test various things. 

So, back to this topic / point: please do whatever you feel may be best here and then give us a quick gif screencast or pictures to just show us what you come up and with since I believe what you're saying would be alright.

**Comment by dmarmor** [comment]
The way I'm picturing this working, you will be able to keep your Epichrome apps anywhere you want, OS and user directory can be on separate volumes, and the only really important thing will be that Epichrome and Chrome will need to live on the same volume (and pretty much Chrome should always live in /Applications, it turns out.

I'm going to try to test this soon, but if it works I'm going to have to change Epichrome's installer package so that it enforces that Epichrome can _only_ be installed under /Applications.

**Comment by ylluminate** [comment]
Alright - so essentially I'm going to plan on keeping Epichrome apps now in `~/Applications/Epichrome/` and will be fine with whatever hierarchical structure you need to generate in this regard. You are also saying that `~/Library/Application Support/Epichrome/Apps` will also live in this new hierarchy beside the engine, right?

Personally I like the idea of a consolidated chunk to keep backed up and archive and backups of an Epichrome app would be simplified as well via a simple folder container.  

I realize that this might seem less "mac-like" to some folks, but I like it and it's more along the idea of a "unix way" of doing things and seems as though it would allow the use of this method on *nix systems generally.

**Comment by dmarmor** [comment]
No, I would leave all other settings and user data in ~/Library/Application Support/Epichrome/Apps. ~/Library is where user data and config settings like that belong on a Mac. All I'd move to /Applications is the engines, which are in fact apps, so there's at least a reasonable argument for them living there. You'd still have to collect items from 2 places rather than 1 in order to back up.

I don't really know Windows very well, having not used it much in many years, but from my recollection, I'm not sure there's a good reason to have Epichrome for Windows, since you can create the equivalent of an app very easily by just making a shortcut to Chromium with the command-line options you want and launch that as you will. Since Windows doesn't have the same type of app bundles and the dock and global menubar, I'm not sure there'd be much use for Epichrome. (Also, I hope never to do any Windows development ever again!)

**Comment by dmarmor** [comment]
As you guys probably know, I did make this architectural change to Epichrome, so as long as Epichrome is installed in /Applications (as is default with the installer package), external Chrome engine apps should work fine with 1Password. Closing this issue for now, but you notice problems let me know and we can reopen.
