### ISSUE TITLE
Migrate from 2.2 to 2.3

### ISSUE THREAD

**Issue by bendehghan** [dmarmor/epichrome#218]
My apps (made with 2.2) have stopped opening. I installed 2.3 and then opened the apps and I still get 

> A new version of Epichrome (2.3) is available on GitHub.

Click on the "Later" and I get this:

> Unable to update app to new version of Google Chrome. (Error filtering Info.plist file. (ascii)) It may or may not run properly.

Is there a migration path? Typically if you do a huge rewrite that is not backwards compatible, you move the version number by a whole. So I would expect this to be a v3, and allow people to stay on v2.x if they need to. Right now I have a bunch of apps that have a bunch of logged in chrome profiles and recreating all that means redoing all the login etc. That defeats the whole purpose of epichrome.

So, 2.2 isn't working. 2.3 can't handle 2.2 apps. Basically I need to start over with everything??

**Comment by dmarmor** [comment]
Hi @bendehghan, downloading and installing Epichrome 2.3.x would not cause your 2.2.x apps to stop working. Also, 2.2.x apps are fully updateable to 2.3.x. Something else has happened to your apps, I'm afraid.

(I'm assuming the GitHub message you saw actually said ```A new version of Epichrome (2.3.0) is available on GitHub.``` or something similar. It couldn't have said 2.3 as that's not a valid version number.)

Can you tell me what actual version those apps are/were? Were they 2.2.4? Also, when you ran them, either before or after the GitHub message, did you see an alert that said ```A new version of the Epichrome runtime was found (2.3.1). Would you like to update now?```

Thanks. Hopefully we can figure out what's gone wrong. If not, I can talk you through how to recreate those apps without losing your settings for each app.

**Comment by bendehghan** [comment]
Ok. I mangled the error message when I typed it back. It was as you wrote (2.3.0). 
I think part of is that my chrome version also got updated. I'm on beta version of chrome. currently 83.0.4103.56 and I think the combination of chrome update and epichrome update has caused some issue. 

I noticed that there is a different folder structure in the two versions. So I manually copied files in ~/Library/Application Support/Epichrome/myapp2.2.4 to ~/Library/Application Support/Epichrome/myapp2.3.1/UserData and then opened the new app. It sort of works. It brings up the windows and tabs as I had them before but none of my profiles info is there. So gmail is logged out.

If I try to open one of the old apps that were 2.2.4 now I get the error 

> A new version of Epichrome (2.3.1) is available on GitHub.

and when I say "Later" I get 

> Unable to update app to new version of Google Chrome. (Error filtering Info.plist file. (ascii)) It may or may not run properly.

Anything short of allowing me to reopen how things were with the previous chrome profiles isn't going to work for me since I'd have to redo all the login stuff. But at the very least it would be nice to be able to get a list of windows and tabs that were open before so I don't lose that info. Maybe that should be part of the upgrade path: 

1) save the list of windows and tabs
2) backup profile info
3) upgrade
4) try to restore profile info
5) restore windows and tabs

The problem with making a good tool is that people will rely on them working! :)

**Comment by dmarmor** [comment]
There are a couple things going on here. The problem you're seeing with apps not running and with the Info.plist error appears to possibly have something to do with the new version of Chrome (you caught it before anybody because you were on the beta). That's described in issue #225 and I'm going to work on it in that thread, so please subscribe there to follow.

I don't think you actually have a problem with the 2.3.1 update, because it appears to me you have not installed it on your system. The fact that you're seeing the message about a new version being available on GitHub means that that version is *not* on your system. So these are still 2.2.4 apps that are not working, and I strongly suspect they're not working because of this new version of Chrome.

When/if you do update an app to 2.3.x, you wil not have to manually move an old 2.2.4 data directory to UserData yourself--that is done automatically by Epichrome during the app update process, and it's strongly recommend you not interfere with it, as it's doing more than just moving the whole directory over.

I ssupect that what happened when you did that yourself is that the old 2.2.4 app then assumed there was no profile and created a new one causing you to lose all your state. You can get it back by quitting the app deleting everything in the data directory *except* the UserData directory you created, and then moving everything in that directory back to the top level of the data directory.

Closing this for now, and will work on the Chrome problem in issue #225.
