### ISSUE TITLE
Unable to launch Chrome when an Epichrome SSB is already running

### ISSUE THREAD

**Issue by steiney001** [dmarmor/epichrome#22]
I think I've seen this mentioned before but I couldn't find a closed issue about it, so I figured it was worth mentioning. It seems that, if I have an Epichrome SSB open, if I try to launch the normal Chrome browser, it just brings to the front whichever Epichrome SSB is currently running that has been used most recently and is the closest to the front of the line in the "Command+Tab" switcher HUD. I'm on Epichrome 2.1.4, for the record.

**Comment by dmarmor** [comment]
Hi @steiney001,

I think someone else did mention this somewhere, but I've never been able to recreate that behavior. Every SSB I've run has no trouble coexisting peacefully with Chrome or other Epichrome SSBs.

Can you give me some more info? What version of OSX are you running? Are you running the latest Chrome? If possible, could you get a screen-shot of the summary dialog for an SSB that exhibits this behavior? (You'd need to re-create it in order to capture the dialog.)

Thanks! Hopefully, we'll get to the bottom of this...

**Comment by steiney001** [comment]
Hey @dmarmor,

I just updated to the latest Chrome (44.0.2403.157 (64-bit)) and the issue stills exists. I'm on OS X 10.9.5. Also, all the SSBs I have running have auto-updated themselves to the latest version of Chrome.

When you say "the summary dialog for an SSB that exhibits this behavior", are you talking about the console log or something else? Nothing pops up, etc. when the behavior occurs, other than one of the running SSBs being brought up to the front of the running apps. But I don't get any error, warning, etc.

Also, I just noticed, the SSB that gets brought to the front when I try to open Chrome is not necessarily the SSB that's closest to the front, as I incorrectly stated before. The behavior seems to get locked to one of the running SSBs, and even if that SSB is furthest in the back, it will be the one that gets brought to the front. Then, if I quit the SSB that is getting affected, then the behavior will effect one of the others that's running, and even if I re-open the SSB that was being affected previously, the behavior will still be tied to the other SSB.

I hope that last paragraph makes sense! It's a bit hard for me to accurately explain without knowing all the technical terms that are supposed to be used. :)

**Comment by dmarmor** [comment]
Well, hmm. Looks like you're up-to-date with Chrome. I wonder if it's possibly to do with being on Mavericks vs. Yosemite, though I doubt that. I originally developed Epichrome on 10.9, and can't think of any reason why it would exhibit this behavior.

What I meant by summary dialog was the dialog you get when you run Epichrome.app itself in order to create the SSB. The last thing you see before it actually creates the SSB is a dialog with all the specifics of the SSB it's about to make. I was hoping I could see if you're using some combination of settings I could recreate to test the behavior. But it sounds like it's happening with *all* your SSBs... Maybe you could send me a sampling of the SSBs? I'd want to recreate them as exactly as possible, so if you could let me know:

- the name and path you saved them to
- the "short name"
- app style (App Window or Browser Tabs)
- exact URL(s)
- whether you registered the SSB as a browser
- custom icon

Sorry it's a lot of info, but I won't be able to diagnose or fix the problem if I can't recreate it on my system...

Thanks!

**Comment by steiney001** [comment]
Hey! Sorry it's taken me so long to get back to you. Here are the 
details of the SSBs I have created with Epichrome that run all the time.

Regarding whether or not I registered each app as a Browser, I honestly 
don't remember which I choose for each. Is there anyway way for me to 
look it up? I tried poking around in the info.plist and in the 
Application Support folder stuff, but didn't find anything. Sorry!

Also, I have an external extension installed in each SSB. Namely, 
1Password. I have an account so I installed the extension on the chance 
that I need to re-enter my password. It's really long.

I don't know if it's worth mentioning but I also have a Fluid based SSB 
running all the time. I can't imagine how that would impact an Epichrome 
based SSB, but just wanting to give you as much info as possible. It's 
the "Google Suite" I told you about. Calender, Contacts and Google Drive.

1. Wunderilst
Name: Wunderlist-Epichrome.app
Path: /Applications/Wunderlist-Epichrome.app
Short name: Wunderlist (I'm assuming here that short name refers to the 
title shown in the upper left corner in the menu bar.)
Style: App Window
URL: https://www.wunderlist.com/#/lists/xxxxxxxxx (I redacted the 
account number at the end of the string. I'm assuming that shouldn't 
matter.)
Custom icon: Yes

2. SimpleNote
Name: SimpleNote-Epichrome.app
Path: /Applications/SimpleNote-Epichrome.app
Short name: SimpleNote
Style: App Window
URL: https://app.simplenote.com/
Custom icon: Yes

3. Remote Messages (This is a cydia app I have on my iPhone that mirrors 
your text message/iMessage through https. It works great with Chrome. I 
connect directly to the phone through the local network with a un/pw combo.)
Name: Remote Messages-Epichrome.app
Path: /Applications/Remote Messages-Epichrome.app
Short name: Remote Messages
Style: App Window
URL: http://192.168.1.43:5818/
Custom icon: Yes

Let me know if you need any other info or if there's a way for me to 
nail down whether not each app was registered as a browser.

**Comment by dmarmor** [comment]
Well...I just recreated all three of those apps, added the 1Password extension to all of them, ran them in various combinations, and I couldn't get Chrome to fail to open.

I tried most of the permutations with the apps *not* registered as browsers. I did try one of the apps registered as a browser, and got the same behavior. Didn't have time to try all the combinations. The way you could check if the apps are registered as browsers on your system:

1. Open System Preferences.
2. Go to the General pref pane.
3. Click the Default web browser drop-down menu.

If your apps are in that list, they're registered as a browser. Let me know if they are and I'll try a fuller test of that. Otherwise, I really don't know what to tell you! I simply can't get the behavior to show up on my system. Maybe try re-installing Chrome and see if that helps? I'm assuming you've already tried the usual rebooting and such?

**Comment by steiney001** [comment]
Yeah, that's strange. I did try the reboot but no luck. I just checked 
and all the SSBs are registered as browsers. I don't want to put you to 
a bunch of work though. It doesn't seem like anyone else (including you) 
is experiencing the issue so it could easily just be something unique to 
my set up. I do quite a bit of tinkering with things. I really 
appreciate the help with it though. I'm still happy as a clam to have 
your app. The three that I am using right now are definitely noticeable 
improvements over their Fluid predecessors. No offense meant to the 
Fluid dev, of course!

I guess I could re-copy the Chrome app into my Applications folder, but 
I'd rather not go through the hassle of doing a complete wipe and 
reinstall of Chrome. I run a business and do everything for the business 
in that browser, so I really don't want to wipe it.

I'll let you know if I happen to figure out what is causing it to occur. 
Thanks again for looking into this!

**Comment by dmarmor** [comment]
Hmm...sorry we couldn't figure it out. If you ever do reinstall Chrome (or update OSX) and it starts working, please let me know. I guess I'll close the issue for now, but ready to reopen if anything comes up.

Thanks again for all the info!
