### ISSUE TITLE
epichrome 2.3.1 chrome apps grabbing URL handler for com.google.Chrome

### ISSUE THREAD

**Issue by gregschroeder** [dmarmor/epichrome#221]
Since I was having some troubles with Brave SSBs, I thought I would try Chrome ones with 2.3.1.

They get created fine, and generally work without the problems of Brave (session state, mic access, etc).  But the URL handling seems to be incorrect.

Basically, the most recently created SSB seizes control as the default 'Chrome' browser.  I usually use Finicky, but this isn't that.  I totally bypass Finicky and try to open directly with Chrome via:

```
open -b com.google.Chrome 'https://yahoo.com'
```

This opens in the most recently created SSB that has external Chrome as the browser and not the default Chrome.

I tried this with both an upgraded 2.2.x app and a brand new 2.3.1 app.  If you select external Chrome, then this happens consistently.

If I go to settings in primary Chrome and attempt to reset the default browser, it doesn't offer Chrome as a choice - only my most recent SSB app name.

**Comment by darrenaalfonso** [comment]
I've experienced the same issue.

**Comment by dmarmor** [comment]
So as I mentioned in the other issue just now, if you've got Chrome-based Epichrome apps on your system, you will always get inconsistent behavior attempting to address com.google.Chrome, because there are multiple different apps on the system with the same ID. This is unfortunately just the nature of these Chrome-based apps (and the reason I created the built-in Brave engine).

So my recommendation for using Finicky would be to try using paths instead of IDs there. I don't use Finicky myself, but I believe @ldub created a merge that allows this and appears to me to have been incorporated:

https://github.com/johnste/finicky/commit/5ff93d50da6b47451388380980fcb50b1b1d9b2d
