### ISSUE TITLE
Generic icon in Dock for Epichrome apps

### ISSUE THREAD

**Issue by alatteri** [dmarmor/epichrome#226]
Hello...
All my apps are showing with the generic icon in the Dock, but they show the proper icon in Finder.

This started with the 2.3 betas.
See attached.
<img width="534" alt="Screen Shot 2020-05-20 at 5 27 33 PM" src="https://user-images.githubusercontent.com/625982/82510458-70325800-9abf-11ea-9323-e7297375b3d6.png">

**Comment by dmarmor** [comment]
Hmm! I'm trying to think how that could happen. Did you give those apps custom icons when you built them by selecting a custom icon in Epichrome, or did you add the custom icon later in the Finder?

**Comment by alatteri** [comment]
Likely after in Finder.

**Comment by alatteri** [comment]
Likely after in Finder.

**Comment by dmarmor** [comment]
Ah, that would explain it. If you do it that way, then if for whatever reason the engine gets rebuilt (as it would be for instance whenever an app updates to a new version of Epichrome) it will revert to the default icon.

Enough folks have tried to do custom icons this way that I'm looking into whether I can have Epichrome detect that during an update and incorporate it. Otherwise, you're probably going to be experiencing this problem until I can add app editing, which I'm planning as my next new feature...

**Comment by alatteri** [comment]
Understood.  Thanks.

**Comment by talleux** [comment]
@alatteri When this happens to me I copy the icon from /Applications/[AppID] to /Applications/Epichrome/EpichromeEngines.noindex/[Macos-USER]/[AppID] using the "Info" menu from the finder for both app folder and copy&paste the icon.

**Comment by talleux** [comment]
FYI: I just had the lost of the icon after updating from 2.3.1. to 2.3.2b2 (Chrome based app)

**Comment by dmarmor** [comment]
Hi @talleux, yeah if you add a custom icon after the fact (by copy-pasting from Get Info) then that icon will be lost whenever the engine is recreated, which happens during every update. Until app-editing is ready, the only way to keep the custom icon permanently is to select it when creating the app in the Epichrome interface. Otherwise, you will have to reinstall it with copy-paste whenever the engine is recreated.

**Comment by talleux** [comment]
Yes @dmarmor so it is. Until this get “fixed” I have my ritual after each update (fixing my icons manually) ;-)

**Comment by empathetics** [comment]
Just a heads up that I have was having a similar issue - #231 - and did try to change the icons within the epichrome subfolder -  /Applications/Epichrome/EpichromeEngines.noindex/[Macos-USER]/[AppName] - but this didn't resolve the issue. Did resolve when I recreated the applications and set custom icon during creation instead of after.

**Comment by talleux** [comment]
@empathetics did you restart the app after fixing the icon?

**Comment by empathetics** [comment]
yup - no jazz.

**Comment by dmarmor** [comment]
Yeah, as I mentioned in the other issue, setting the icon during app creation is the only way to make it work reliably...

**Comment by christefano** [comment]
Not to hijack this issue… I also used to copy / paste custom icons in the Finder (well, Path Finder), and when this didn’t work I set the icon during app creation for a Nextcloud SSB. I still see a generic icon. 

The image I used was this PNG with a transparent background: https://www.scaleuptech.com/de/wp-content/uploads/2019/08/round.png

**Comment by dmarmor** [comment]
Hi @christefano -- do you see the generic icon in both the dock and the app switcher? How about looking at the main app in the Finder? If possible, could you zip up the app (not the engine app, just the main one which should only be about 1.5-2MB) and upload it to me here:

https://www.dropbox.com/request/xdujaepeWCgt2NYN5q7o

Thanks!

**Comment by christefano** [comment]
You got it. I uploaded Hub.app.zip just a moment ago.

> do you see the generic icon in both the dock and the app switcher? How about looking at the main app in the Finder? 

Custom icon in the Finder, generic icon in the Dock and Command-Tab app switcher (sorry, couldn’t think of anything that rhymes with Finder).

**Comment by christefano** [comment]
> When you say "generic icon" do you mean the default Epichrome icon? Or some other generic icon?

Yes, the default Epichrome icon.

> Also, is there any possibility you have a duplicate copy of this app anywhere on your system without a custom icon?

Yes, I found another Hub.app in the Epichrome folder, and I gave that a custom icon. I didn’t realize there was another copy somewhere!

(When I open ~/Applications/Hub.app it seems to open the app in ~/Applications/Epichrome/EpichromeEngines.noindex/Hub/Hub.app)

**Comment by dmarmor** [comment]
Aha, OK, so if you get rid of the one with the generic icon (or the one that wasn't created with a custom icon through the Epichrome interface) and delete the engine directory (`~/Applications/Epichrome/EpichromeEngines.noindex/Hub`), then run the app with the custom icon, do you see any improvement?

**Comment by christefano** [comment]
Not sure I follow 100%, so my apologies if I come across as unclear. 

I deleted the entire folder at `~/Applications/Epichrome/EpichromeEngines.noindex/Hub` and relaunched the SSB at `~/Applications/Hub`, and it re-created the app at `~/Applications/Epichrome/EpichromeEngines.noindex/Hub` with a generic icon.

I gave it a custom icon and am content with that for now. I’ll try to continue helping troubleshoot this, and I might be delayed due to other things.

**Comment by dmarmor** [comment]
That is very puzzling! Assuming the app at ~/Applications/Hub.app is the same one you zipped up and sent me, I cannot figure out how that could possibly be creating an engine with a generic icon. Once I've got app editing working it'll be easier to fix these issues, so hopefully your workaround copying in the custom icon will work till then.

**Comment by brianfmorris** [comment]
I am noticing some very similar behavior with an interesting twist.
I have created app with custom icon at time of creation [Amazon.app].  The icon appears correct in ~/Applications/ and ~/Applications/Epichrome/EpichromeEngines.noindex/ 
<img width="194" alt="Screen Shot 2020-08-24 at 9 58 05 PM" src="https://user-images.githubusercontent.com/38328553/91114169-460bab80-e655-11ea-8543-fbe6ac19e015.png">
<img width="245" alt="Screen Shot 2020-08-24 at 9 57 40 PM" src="https://user-images.githubusercontent.com/38328553/91114183-4f951380-e655-11ea-8e4c-da3b8e19c63e.png">

I added the app to the doc where the icon appears correct
<img width="86" alt="Screen Shot 2020-08-24 at 10 03 05 PM" src="https://user-images.githubusercontent.com/38328553/91114336-a995d900-e655-11ea-9a55-30b37069759f.png">

when I launch the app, the icon in ~/Applications/Epichrome/EpichromeEngines.noindex/ changes to the chrome icon
<img width="157" alt="Screen Shot 2020-08-24 at 9 58 16 PM" src="https://user-images.githubusercontent.com/38328553/91114251-7a7f6780-e655-11ea-8140-5c8593d4af47.png">

and a new app launches in the doc (ie not the app I copied from ~/Applications/) with the Chrome icon
<img width="119" alt="Screen Shot 2020-08-24 at 9 58 22 PM" src="https://user-images.githubusercontent.com/38328553/91114366-bd413f80-e655-11ea-8e63-1833859ed15e.png">

When I quit it gets weird again --- the icon in ~/Applications/Epichrome/EpichromeEngines.noindex/ changes back to the original Amazon icon.

I'm not sure if any of this helps, but hoping it might.  I'm using Epichrome 2.3.8, OSX 10.14.6

**Comment by dmarmor** [comment]
Hi @brianfmorris -- first off, with Epichrome 2.3.x, the app you should keep in the dock is the one in EpichromeEngines.noindex, not the one in ~/Applications. The easiest way to make sure it's the right one is to run the app, and then find its icon in the dock and choose `Options->Keep In Dock`.

As for the icon problem you're having, that is very puzzling. At worst, I'd expect that icon to be a generic Epichrome one, but not a Chrome one! The first thing to do would be to delete the app's engine so the app can recreate it. Make sure the app is not running, and then delete the entire folder `~/Applications/Epichrome/EpichromeEngines.noindex/<YourApp>`. Then run the app again. It'll take a while to run the first time as it rebuilds the engine, but then hopefully the problem will be fixed.

Can you let me know if that helps?

**Comment by brianfmorris** [comment]
That seems to have addressed the icon issue.  Thanks!

**Comment by dmarmor** [comment]
Excellent, glad to hear it, @brianfmorris!

**Comment by aagarw33** [comment]
@dmarmor I am on 2.3.9, I created a brand new app with a custom icon during app creation, the custom icon is available in ~/Applications/. but in dock and notifications, I see the generic epichrome icon I am using built-in brave browser.
Could you please help?
Thanks.

**Comment by aagarw33** [comment]
@dmarmor nvm, I was using `.png` using `.icns` works perfectly.

**Comment by dmarmor** [comment]
Hmm, this is odd. PNG files should work just fine as a source for icons, as Epichrome can convert PNGs to ICNS. If there were any problem with the PNG file you selected in Epichrome.app, it should give an error.

Can you tell me any more about the problem and your solution? If I understand correctly, it sounds like you created an app in Epichrome.app, selecting a PNG file during that process to use as a custom icon. Then when you the app was created, it had the correct custom icon, but when you run the app, you see a generic icon in the dock and notifications. Is that right?

And you resolved this by recreating the app, but instead of feeding Epichrome.app a PNG, you fed it an ICNS file?

If that's all correct, I would love to have you try the process again with the PNG file to confirm it still has the same problem, and if so I'd love to try creating an app with the same PNG file to see if I can figure out what's going on.

Thanks!

**Comment by talleux** [comment]
Is this maybe related to #290 ?

**Comment by dmarmor** [comment]
Hi all, I think there are two separate issues going on here, which I'm going to separate into two issues.

1. (This issue, #226): If you set a custom icon for your app using the Finder after creation, it will lose that icon when you update the app. There's nothing I can do about this, as the app bundle gets recreated on update. The way to set a custom icon for an app is during creation (or editing once 2.4.0 is released). So I'm going to close this issue.

2. (Issue #290): This is something else I haven't been able to diagnose, when apps with properly set custom icons lose their icon. I'd like to move all discussion of that scenario to that issue.

Thanks!
