### ISSUE TITLE
Emptying cache folders?

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#238]
When i currently backup my apps, especially because of current bugs, under which is #232, i need to backup these 2 folders:
`/Applications/Epichrome/EpichromeEngines.noindex/<USER>/`
`~/Library/Application Support/Epichrome/Apps/`

I have 29 apps and these 2 folders have respectively 7GB and 9GB so each backup is about 16GB..
Are there any caches files or folders that i could safely deleted from my backups or even from the productive folders like to clean a bit some old stuff and save some space?

**Comment by dmarmor** [comment]
Really you should only back up the app itself and the data directory (in `~/Library/Application Support/Epichrome/Apps/`). You should definitely not back up the engine, and can safely delete all your backups of engine directories. The engine is automatically created by the app when it's run anyway, and if you're having problems then like the engine needs to be rebuilt anyway. It's actually not a bad idea if you're having problems with an app to delete its engine directory entirely. The next time you run the app it will be recreated.

Another reason not to back up the engine, is that even though each engine looks very large, they are not each taking up space on your hard drive. When an app creates its engine it does so by hard-linking to the original Chrome or to the Brave engine built into Epichrome. So those engines do not take up very much extra hard drive space at all--unless you copy one. If you do that, then the copy will take up all that space.

(Note that if you're using the built-in Brave engine, then the app *must* have the same version of Epichrome installed on the system in order to rebuild the engine--if you've installed a new version and have an older app whose engine is gone, the app will not be able to run until it is updated to the new version.)
