### ISSUE TITLE
Epichrome Apps Don't Launch in App Window Mode

### ISSUE THREAD

**Issue by Jake3231** [dmarmor/epichrome#24]
Hi!  I love the Epichrome app, but have noticed one small bug.  After creating one test app, all of my apps that I make will not launch in the app window mode.  They also just open to google.com instead of the specified page (which is chrome://apps).  I will list how I set up the app below.  Also, if you don't mind me asking, how did you get the app to register the user-created apps as a browser?

Name "Google Apps"
Path: Desktop
App Style: "App Window"
URL "chrome://apps"
Registered as browser
Default Icon

**Comment by dmarmor** [comment]
Well, I can get part of your problem to appear on my system--when I recreated the app you specified, it won't open an app-mode window. This turns out to be a limitation of Chrome's command-line. When I try to launch Chrome with any chrome:// page on the command-line, it refuses to open it.

I'm not sure I'll be able to solve this to your satisfaction. I'll add it to my to-do list, but the solution would be for the system to detect that the specified URL(s) are chrome:// schemes, and then use the helper extension to force them open. It would be a lot of work, and I suspect prone to error, but if I get time I'll see if I can make it work.

As for the behavior you're seeing where none of your other Epichrome apps are working, I couldn't get that to happen at all. I can't see a reason why the failure of one to open its app window properly would affect the others. Are your other apps opening normal http:// or https:// pages? Does it matter if you have other Epichrome apps open before you run the "Google Apps" one?

**Comment by dmarmor** [comment]
Oh--forgot to answer your other question, how to get an app to register as a browser. You have to include a few specific keys in the Info.plist file: CFBundleURLTypes, NSPrincipalClass and NSUserActivityTypes. If you look at the Info.plist for any Epichrome app that's registered as a browser, you can see what would need to be in those keys.

**Comment by Jake3231** [comment]
Sorry for the late response. If I understand, I cannot create an app using any "chrome://" URL?  To answer your question, all of the apps I attempted to make were using the "chrome://apps" URL. I haven't tried running other Epichrome apps with the "Google Apps" one...

**Comment by dmarmor** [comment]
Yeah, that's what it seems like. It's a limitation with Chrome. Epichrome works by launching the underlying Chrome binary with command-line options, and uses the --app option to get the app-mode window behavior. You can try it yourself from the terminal:

"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --app=https://www.google.com/

But if you give the --app option a chrome:// scheme, it just won't open an app window.

I'll close the issue for now, because I'm just not sure I can find a way to solve it, but it's on my internal to-do list to see if there's some reasonable workaround. Sorry I couldn't be more helpful on this one!

**Comment by Jake3231** [comment]
I appreciate your help on this. I am glad to have a good answer, and I'm glad to know that you are aware of this. Thanks for helping me understand that.
