### ISSUE TITLE
Tip on getting rid of Little Snitch alert after updates of apps

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#241]
After each update of an app to the newest version of Epichrome Little Snitch sees it as a new application. For each single app of course. I need to confirm 1) to allow internet connection and 2) that the new code signature is ok.
Any idea if there is a way getting rid of this?

**Comment by dmarmor** [comment]
I haven't used Little Snitch, but I'm surprised if it handles Epichrome app updates differently than, say, Chrome updates. Does it not require these confirmations when Chrome updates itself?

Unfortunately, I don't know if I can do anything about this behavior. When an app updates, it is basically recreated in order to use the current Epichrome release. I have recently started codesigning the main app executable and the built-in engine executable (in 2.3.2b1 I think). Are you still seeing the problem when updating to 2.3.2b1 or 2.3.2b2?

Also, this might be difficult to know, but do you have any idea if it's asking for this confirmation for the main app, or the app engine? That would be important to know in terms of figuring out if this might be fixable.

**Comment by talleux** [comment]
@dmarmor 
No, Little Snitch doesn't "see" new versions of Chrome as new app, but yes, for each Epichrome App it does.
I imagine that you may have no way to change this and it's not a very big issue. Nevertheless using a lot of apps and having updates frequently this leads to a bunch of dialog boxes to interact with quite often. LittleSnitch asks me at least 2 times to confirm authorization per App.
If you are interested i can document more detailed the next time.

**Comment by dmarmor** [comment]
Yeah, unfortunately, there won't be any way for me to fix this. If it sees updates of Chrome as new apps, then it will unfortunately do the same with each Chrome-based app (as well as Brave-based apps, I'd assume). I'm sorry it's irritating, but I can't think of any way to defeat it, unless there's some setting in Little Snitch itself that would ease the authorizations.

Honestly, it kind of seems like a bug to me that it should think every update to an app is a new app. Maybe the developer of Little Snitch can fix that behavior?

Closing for now, but if you have more info that seems to indicate I might be able to do something about this, let me know and we can reopen.
