### ISSUE TITLE
CopyLess get wrong icon from app

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#242]
Since the update to 2.3 (i think!) CopyLess always uses the icon of the same app for entries copied in _any_ of my chrome based app as well as stuff copied in Google Chrome itself (!).

It uses the icon of the app that is the first in the alphabetic order.

This bug wasn't there in 2.2

**Comment by dmarmor** [comment]
This is one of those things I cannot fix with Chrome-based apps, and is one of the reasons I created the built-in Brave engine. You should not have any problems with icon confusion with the built-in engine, which is why I generally recommend it for new apps. As far as Chrome-based apps, if an app interacting with it decides it wants to address the app by its bundle ID, then it will always cause confusion between the real Chrome and the apps, and it's not something I can control.

So I'm sorry not to have a better answer for you here, but the only real workarounds will be to either switch to the Brave engine for apps you want to use CopyLess with, or contact the makers of that software and ask if they can change how they pick up the icon so it doesn't get confused.
