### ISSUE TITLE
Changing app language not possible per app - and macOS mixes the icon

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#243]
I wanted to change the language of on app and found this:
https://beebom.com/how-customize-language-settings-specific-apps-macos-catalina/
Doing this for a specific chrome based epichrome app it says, this app has no other languages. Ok, this may be a specific feature to be implemented in epichrome or even not feasable.

When i change the language of Google Chrome, the language of all chrome based epichrome apps is switched. Which i can understand.

Confirming the setting in mac ask to restart the browser. This will close _all_ chrome based epichrome app. Again: Which i can understand and don't expect to work better but can be important to know.

The strange thing is: the icon in the mac setting changes from time to time between the ones from epichrome apps but isn't the one from Google Chrome:

![image](https://user-images.githubusercontent.com/5243081/83328437-5d6c1000-a283-11ea-84ce-614bad87bcda.png)

This may be related to #242 

This isn't a real issue for me but just to give some infos that may be usefull.

**Comment by dmarmor** [comment]
This is the same issue as you're having with CopyLess. Because the language system is using bundle ID to decide which language settings to apply, all your Chrome-based apps will have the same settings, and it will choose the icon to show more or less at random from among your Chrome-based apps (or by some system that clearly is not repeatable or reliable).
