### ISSUE TITLE
Right steps to update Google Chrome

### ISSUE THREAD

**Issue by seroy** [dmarmor/epichrome#267]
The readme says that is not recommended to using Chrome update functionality, but what is right way to update on new version Google Chrome?

**Comment by dmarmor** [comment]
The option you should definitely not use is "Automatically update Chrome for all users" which is in the About Chrome page. That installs an admin-level tool that handles updates, and seriously screws up Chrome-based Epichrome apps.

As long as that option is off, you can update Chrome as you normally would (it usually just auto-updates itself when you relaunch it). If you ever notice your apps acting oddly or not working properly, often that's because Chrome is in the middle of updating itself. On my own system, when I notice that there's an update available for Chrome (you'll see a little orange arrow icon instead of the usual ... menu at the top right of the window, just below the tab bar), I quit all my Chrome-based Epichrome apps, restart Chrome to install the update, then restart my apps. The apps will then recognize that Chrome has been updated, and will recreate their engines accordingly.
