### ISSUE TITLE
Does 1Password 7 work?

### ISSUE THREAD

**Issue by kevinapp** [dmarmor/epichrome#268]
I can't seem to make 1Password 7 work with Epichrome. Is this still possible?

**Comment by grouchal** [comment]
@dmarmor  The 1password normally works for Brave though - is there a way to get Brave to work with Epichrome and 1password - maybe when it is installed in `/Applications`?. The problem for me is the lack of touchID support in 1passwordX (plus the extra work to get it setup in each new epichrome app).

**Comment by dmarmor** [comment]
Hi @grouchal -- No, the 1Password will only talk to the desktop software if it's running in a browser it recognizes. Since Chrome-based Epichrome apps are running the full, signed Chrome, they can do this. But Brave-based apps have their own bundle ID (which is one of their main advantages) so 1Password will not recognize them as valid for talking to the desktop app.
