### ISSUE TITLE
Extra tabs opening every time I open the app

### ISSUE THREAD

**Issue by anthonysapien** [dmarmor/epichrome#270]
This has been occurring for a while on the latest stable and beta branches, currently on 2.4.0b1.

My app is running on the latest Mac OS on Brave with browser tabs (not single app window) and has 3 tabs configured to open. When I open my app, the tabs that were open during my last session stay open and 3 new configured tabs open.

I can follow these steps to reproduce:
1. Open the app
2. Close all tabs
3. Close the app
4. Open the app. 3 tabs open
5. Close the app
6. Open the app. 3 previous tabs are open, and 3 new tabs open

So repeating this, I have 3, 6, 9, 12, ... tabs open.

Please let me know if I can provide any further details. Thanks.

**Comment by dmarmor** [comment]
Hi @anthonysapien,

This looks like a problem where, for some reason, Epichrome was not able to set its default preferences when the app was created. There is a bug in 2.3.x that can make that happen, which I've fixed for the upcoming 2.4.0 release. But that of course will only apply to newly-created apps.

Luckily, for existing apps the fix is easy:

1. Run the app. Once it's running, open the app's preferences (`Command-,` or `Preferences...` from the <AppName> menu just to the right of the Apple menu).

1. At the top of the preferences page, you should see an `On startup` item. Change it from `Continue where you left off` to `Open the New Tab page`.

1. Restart the app, and it should only open your selected tabs.

Please let me know if that works for you!

**Comment by anthonysapien** [comment]
All set and glad that will not occur for new apps with the new release. Thank you!

**Comment by dmarmor** [comment]
Glad that fix worked!
