### ISSUE TITLE
Wrong bundle identifier for the apps generated in EpichromeEngines.noindex

### ISSUE THREAD

**Issue by grigorye** [dmarmor/epichrome#274]
The bundle identifier for the apps generated in EpichromeEngines.noindex (in Chrome mode) is `com.google.Chrome`, while the "original" SSBs generated have bundle identifier that looks like `org.epichrome.app.<SSBName>`.

This makes those apps interfer with "real" Google Chrome, when another app tries to open Chrome by using the bundle identifier - what I observe is that app from EpichromeEngines.noindex gets open instead. You can try to reproduce it via the following steps:

1. Make sure you have Chrome installed
2. Open an existing SSB
3. Try `open -b com.google.Chrome`

At this point the SSB from EpichromeEngines.noindex will be activated instead of Chrome. In my case, SSB is even launched, instead of Chrome, if I omit step 2.

**Comment by dmarmor** [comment]
Hi @grigorye, this is the expected behavior. As outlined in the documentation, this is one of the drawbacks of the external Chrome engine vs. the built-in Brave engine. The way it works, the running app with an external Chrome engine _must_ have the default Chrome ID. Thus, you will never be able to address your running app by ID without the system getting confused with the real Chrome. In most cases, you can get around this by addressing the app by its full path, for example:

```
open -a ~/Applications/<YourApp>.app
```

But if you absolutely must have an app you can address by ID, then the only option is to use the built-in Brave engine.

**Comment by grigorye** [comment]
That's a pity, because it used to be that way, if I recall it correctly. Also, SSBs generated from Chrome still retain the proper bundle identifier, but *now* .apps from EpichromeEngines.noindex become the apps actually running (with the "erased" identifier).

This is not directly related but *now* if you launch SSB and then select to "keep it in Dock", it will retain the .app from EpichromeEngines.noindex, not from the original SSB location - that's also a problem, because that's not what I expect as end user in many scenarios.

**Comment by dmarmor** [comment]
Well, no, A running Epichrome app with a Chrome engine has always had com.google.Chrome as its ID, at least since Mojave. Chrome will not run if its Info.plist is altered at all.

The SSB you run in the 2.3 archetecture does indeed have its own unique ID, but that is just a launcher for the engine. I set it up to make that as seamless as possible (you can for instance send a URL to the SSB and it will pass it on to its running engine), but after it launches the engine, it quits. And you are correct, the app you "keep in dock" is in fact the engine and not the launcher.

The archetecture is changing in 2.4 to make it more unified and will do away with _some_ of the issues you're having. The app you keep in the dock will be the same as the one you create, and there isn't any longer a separate engine app. (This approach has its own problems, but on the whole for most users is simpler and better, which is why I've moved to it.) However, it will not change the underlying issue of the ID of a running Chrome engine. There's simply nothing I can do about that.
