### ISSUE TITLE
Global settings for mic and camera is shared with chrome

### ISSUE THREAD

**Issue by bendehghan** [dmarmor/epichrome#278]
I've been using epichrome for years :)

I have multiple apps. One specifically for my gmail with multiple accounts logged in. I also use normal chrome for browsing. 

When I go to my Mac (Catalina) privacy and security settings, I see the "gmail" app there but not "chrome". But the settings for mic and camera controls both "gmail" and "chrome". 

Question 1) why isn't chrome listed also? I would think chrome should be listed and also "gmail" and also whatever other app I create with epichrome so I can control mic and camera separately for each.

Question 2) why is setting for one, changes the block/access for both?

Question 3 for anyone on mac) Why isn't safari listed in the global privacy and security settings anymore? It looks like all the controls for safari are now inside safari. I don't see a way to block mic for all of safari without going into safari and blocking it for each site.

Thanks guys!

**Comment by dmarmor** [comment]
Hi @bendehghan,

The answer to questions 1 and 2 is the same: this is because Chrome-based Epichrome apps are basically just wrappers around instances of Chrome. When they are running, they are indistinguishable from the real Chrome in every way except their icons and names. MacOS determines resource access by app bundle ID and these apps all use Chrome's ID, so the system will show a random one in the security pref pane, and changing the permission for one changes it for all, including the real Chrome.

This is one of the big reasons I added the Brave-based internal engine in Epichrome 2.3. Apps created with that engine have unique IDs so they can have their own resource access permissions and the system won't get confused. So if this is important to you, the best bet would be to switch those apps to the Brave engine. This can be done in 2.3 with a little terminal magic (I can tell you how) or if you can wait until the upcoming 2.4 it'll be a much more straightforward process, as 2.4 apps are editable.

As for question 3, I have no idea! You'd have to ask Apple, I guess. Perhaps in their arcane wisdom they decided that Safari is part of they system and shouldn't mix with the _common_ apps...?
