### ISSUE TITLE
Script and Document a way to create epichrome apps via the CLI

### ISSUE THREAD

**Issue by RichardBronosky** [dmarmor/epichrome#298]
I'm going to be making so many of these that I really ought to be doing it in a for loop.

**Comment by dmarmor** [comment]
This has been on my to-do list for a long time, but it's kind of a lot of work for something I'm not sure many people really would use that much.

For now, if you really are going to be doing a lot of these, and you're a bit code-savvy, I'd recommend you look at `main.js` and `epichrome.sh` in the sources. `epichrome.sh` is the script that actually builds an app, and it can be run from the command-line no problem. It just doesn't have an especially friendly CLI since it's designed to be invoked from the app. Instead of arguments, it takes environment variable settings of the form `'x=y'` or for arrays, `'x=(' 'a' 'b' 'c' ')'`.

I wrote an internal test script once that did this, which might be helpful in getting you started, as it at least shows you all the variables you'd need to set:

```
epichrome.sh "myLogFile=$myLogFile" 'epiAction=build' \
            "$epiAppPathVar=$myAppPath" \
            "epiUpdateMessage=Building test app \"${myAppPath##*/}\"" \
            "CFBundleDisplayName=$CFBundleDisplayName" \
            "CFBundleName=$myID" \
            "SSBIdentifier=$myID" \
            "SSBCustomIcon=Yes" \
            "$epiIconSourceVar=$myScriptDir/icons/${engine}_$style.icns" \
            "SSBRegisterBrowser=$SSBRegisterBrowser" \
            "SSBEngineType=$SSBEngineType" \
            'SSBCommandLine=(' \
            "${myAppCmdLine[@]}" ')'
```

I hope that's helpful!
