### ISSUE TITLE
Diverting app-external link clicks to standard browser?

### ISSUE THREAD

**Issue by treyharris** [dmarmor/epichrome#3]
I'm wondering what, if anything, can be done to more closely emulate the behavior of purpose-built SSB's like Fluid where you can simply click on links with hrefs external to the app to cause the link to be sent to another browser and not the SSB?

So far as I know the current choices when you _know_ you want to open a link are kind of grim, as summarized in this diagram:

![launching an external browser from a chrome ssb](https://cloud.githubusercontent.com/assets/97895/7188419/a0908e76-e445-11e4-9789-fa7927f63aa4.png)

1. Select the link, right-click, select _Copy Link Address_, and paste the link into another browser;
2. Select the link, right-click and move to the _Services_ sub-menu (or select and use the _Services_ menu in the Chrome SSB menu), and select an Open URL service (which you must have previously set up first);
3. Install an extension such as [Choosy's](http://www.choosyosx.com/) that lets you launch an alternative browser from the link's contextual menu; or
4. Select the link, hit ⌘C (Copy), ⌘⇥ to the desired browser, ⌘T (New Tab), ⌘V (Paste).

The situation is even worse, of course, when you don’t realize ahead of time that the thing you're about to click is going to bring up a new browser window or tab.

**Make Chrome SSB** has a lot of advantages over WebKit solutions like Fluid, the most important being its Chrome backend allowing the use of essential extensions such as password vaults. But the hassle of dealing with external links is a big frictional drag. Is there even a _possible_ solution, even if you cannot commit to it? I don't know enough about Chrome guts to make a swag, but I'm hoping it's possible to do something with Chrome extensions and/or custom stylesheets to get this behavior.

**Comment by dmarmor** [comment]
Hi Trey,

Thanks for writing. I've had this frustration too using the SSBs, but haven't found a good solution. The way the SSBs work, they're really just instances of Chrome with a different app wrapper, so I can't change how Chrome handles internal link clicks.

I've been testing Choosy since you brought it to my attention, and it's OK, but it's not ideal in that it's a pay app, and you still have to right-click to tell it to open a different browser.

I think the right solution would be a dedicated Chrome extension that would filter URLs based on a pattern and let you choose which ones you want to automatically open in a different browser. Unfortunately I have no experience with writing Chrome extensions, and it may be beyond my expertise. I'll look into it a little more and if it seems feasible, I can add it to the to-do list.

**Comment by phillip-r** [comment]
First... thank you for making this simple to install and use tool, so great for the many reasons Trey mentioned above and more.
This diverting functionality would be incredibly appreciated and more than likely be a feature/add-on to the existing app that many of us would be more than willing to pay for... I know I would!  Heck, I'd even commit to buying some pizzas/beers/whathaveyous to get you there if it would help.

**Comment by dmarmor** [comment]
Thanks Phillip! A link-handling extension is at the top of my to-do list now, so it'll just depend on how fast I can learn to write a Chrome extension and how complicated the job turns out to be. I appreciate the offer of pizza & beer--I figure I've gotten so much out of so many great github projects I'm happy to consider this project a kind of karmic payment. What I'd definitely appreciate is bug reports and feature ideas as the project moves forward. I just want it to be as useful as possible to as many people as possible.

Cheers!
  Dave

**Comment by cbeams** [comment]
Hey @dmarmor, I'm a long-time Fluid + Choosy user and have been looking for a Chrome/Chromium-based alternative for a long time. Thanks for putting this project together!

As you may know, Fluid supports constraining URLs that an SSB can handle with its 'Whitelist' settings. This is essential functionality, IMO. Without it, one quickly ends up with SSBs that actually aren't "site-specific" anymore—that is, you end up with little more than a bunch of different browser instances, each with tabs from many different sites open.

When I'm in a Fluid-based SSB and I click a link that is not in that SSB's whitelist, the default browser for the OS picks up handling that link. Since the default browser on my machine is Choosy, the link gets routed to the correct place (often another Fluid-based SSB, or otherwise, to Chromium).

Choosy is not ideal, I agree—not so much because it's for-pay, but because it seems to be abandoned. However, I've found nothing to replace it, and it works perfectly well.

I'll continue to use Fluid for the time being, because the workflow I mentioned above is essential to me, but I hope this description helps in finding a way to emulate it with Chrome-based SSBs.

And thanks, @treyharris for creating this issue in the first place.

**Comment by dmarmor** [comment]
Hey @cbeams, thanks for your comment. Yeah, I'm a former Fluid user myself, and created this project out of frustration with how poorly it seems to work with many modern sites.

Now that version 2 is out, I'm actively working on how to create a Chrome extension with this link-redirection functionality. I think it will be feasible. Most likely the first version will only be able to send links to the default browser, but it might get fancier after that.

I hadn't thought of having links routed from one SSB to another--that could be interesting, though I'm not certain how it would work. You wouldn't want a link to stomp on what you already had open in the app window of another SSB, right? How would you envision that feature working?

Thanks!

**Comment by cbeams** [comment]
> Most likely the first version will only be able to send links to the default browser, but it might get fancier after that.

I think this is all you would need. If you always route links clicked in the SSB to the default browser—and the default browser is Choosy (or something like it), then everything should work.


> I hadn't thought of having links routed from one SSB to another--that could be interesting, though I'm not certain how it would work.

I actually didn't have direct SSB-to-SSB link routing in mind. Again, I prefer centralizing these rules in Choosy and making it the default browser.


> You wouldn't want a link to stomp on what you already had open in the app window of another SSB, right? How would you envision that feature working?

As you may recall, Fluid has an option for how to treat new inbound links to an existing SSB instance. Option 1 is "overwrite the current tab"; option 2 is "open a new tab". And indeed, I use both of these options, depending on the nature of the site/app being encapsulated by a given SSB. I don't know if it's possible to hook into Chrome in such a way that this behavior can be controlled, but if so, I'd say "just do exactly what Fluid does" here.

**Comment by dmarmor** [comment]
Thanks, @cbeams, that's helpful. I've got a prototype extension successfully redirecting links to the default browser, so I know that can be done! There will be a lot of development to get it all configurable per-SSB and easily installable, but it looks like it will work.

Having it emulate Fluid's ability to either overwrite the current tab or open a new tab will take more work--and may not be possible with Choosy as the intermediary (I'm not sure I can capture and recognize an incoming link as distinct from one generated within the SSB). It might be possible to have the extension route between SSBs itself, in which case I would be able to tell each one how to handle incoming links.

That will probably have to wait for version 2...

**Comment by cbeams** [comment]
Sounds good. The latter is just a nice-to-have anyway. Looking forward to trying this out!

**Comment by dmarmor** [comment]
Hi guys,

I just posted version 2.1.0 of the app (I renamed it Epichrome because MakeChromeSSB was too much of a mouthful). This version includes an extension that auto-installs and should do most if not all of what this issue was about.

Please give it a try and let me know how it works for you, and if you find any problems with it.

Thanks!
  Dave

**Comment by treyharris** [comment]
A very belated response—my new job's use of GitHub is such that I inadvertently filtered away a lot of notifications I shouldn't have—but I just wanted to thank you, @dmarmor for Epichrome—absolutely fantastic! Totally meets all my desired features. Awesome!

**Comment by dmarmor** [comment]
Hey, that's awesome! Thanks for checking in--I'm glad it's working for you. Keep the feedback coming (as you have with the "View ..." button issue)...

**Comment by jslez** [comment]
Hi! I love EpiChrome and it's just the best thing ever. I now have dedicated SSBs for different web apps - Gmail, Facebook, Google Calendar. The EpiChrome Helper lets me choose how to handle links in each SSB, which is great. But there seems to be one limitation that gets in the way: the only two handling options seem to be either to open them in the current SSB or the default browser. If I'm in the calendar SSB and follow a link to a Facebook invitation, I need to be able to send it to my dedicated Facebook browser.

It seems like it could be feasible just to add an "Other…" option, which opens a filepicker dialog box and lets me choose the app I need to send that pattern of URL to?

**Comment by cbeams** [comment]
@jslez, consider using https://www.choosyosx.com as your default browser.

**Comment by dmarmor** [comment]
Yes, Choosy or Browser Fairy are good solutions for this.

**Comment by jslez** [comment]
Thanks guys!
