### ISSUE TITLE
Excessive repaints consuming CPU on MBP Retina

### ISSUE THREAD

**Issue by mhwinkler** [dmarmor/epichrome#31]
First of all - I love this app and get a ton of use out of it. Thank you for the work you have put into it!

I recently "upgraded" to OS X El Captian and what I'll describe below is one out of a host of new issues that I got saddled with.

I'm having an issue on 15" Retina MBP running El Capitan using an app created with Epichrome 2.1.6. The app is designed to open a few different Trello boards in a tabbed browser environment. However, upon opening & closing Trello cards, when I'm on a retina screen I get a crazy jittery experience with tons and tons of glitchy repainting that flickering elements in and out of the page.

I did a side-by-side with Activity Monitor and running the exact same page on Chrome 46.0.2490.71 (with a ton of background tabs open) and when I continuously mouseover things causing repaints my CPU usage for the Chrome Helper hovers around 21% and for Chrome hovers around 22%. 

Running on my Epichrome app which also runs Chrome 46.0.2490.71, I open the same Trello page and flick the mouse around causing repaints. However, the repaints are visible in the form of slow big square UI "glitches" around the cursor. The CPU usage for "Trello" (the name of my Epichrome app) hovers around 84% while the Chrome Helper hovers around 12%.

I'm on a retina display that is set to "scaled" which "looks like" 1920x1200. The problem goes away when I plug in an external monitor and use the site at 1920x1080 non-retina. It also goes away when I change the retina display to be at the "default" scaling which "looks like" 1440x900.

My primary source of confusion is that I can do this side-by-side with the same page in Chrome and I don't have the issue at all. Is there something different about Chrome running inside the Epichrome wrapper?

I have attempted:
* Change screen resolutions (results indicated above)
* Non-retina screen (results indicated above)
* Disable Epichrome Helper 1.1.1 (no difference in performance)
* Go to chrome://flags and reset all to default in both Chrome / Epichrome (no difference in performance)
* Verify that "Use Hardware acceleration" is turned on in both Chrome / Epichrome

Any suggestions or insight into the differences between a Chrome instance and an Epichrome instance would be appreciated.

**Comment by dmarmor** [comment]
Hi Matt,

Thanks for the feedback! I unfortunately don't own a retina-display Mac, so I haven't been able to replicate the problem. I did create a Trello app with three tabs open to boards and flicked the mouse around, but they worked fine on my non-retina displays.

The problem clearly has something to do with the app's attempt to handle the retina display, so here's an experiment to try (it'll involve a little surgery on your Trello Epichrome app). First make sure your Trello app is not running, then edit its Info.plist file. That can be found in:

```bash
<path-to-your-app>/Contents/Info.plist
```

If you want to be safe, make a backup of the file first, then open it in whatever editor you like, and remove these lines (which can be found at the very end of the file):

```xml
<key>NSHighResolutionCapable</key>
<true/>
```

I added that key a few versions ago in response to an issue where Epichrome apps weren't opening in high resolution on retina displays. I've never felt totally comfortable with it, since the key does not appear in Chrome's own Info.plist. It might be that it's messing something up when you have your retina display set to "scaled."

Anyway, give it a shot and see if it helps. Either way, please let me know what happens and we'll work on it from there.

**Comment by mhwinkler** [comment]
I appreciate your willingness to investigate even without being able to reproduce the bug yourself - I know that's an annoying task. I made the suggested update to my `<app>/Contents/Info.plist` file and then relaunched the app - no change. To my surprise, there was literally no change in behavior - the app still appears to support retina even without that `NSHighResolutionCapable` property. Perhaps something changed with either Chrome or recent versions of OS X with regard to default retina support in apps?

To give you some more information, I took a screen capture to try to indicate what's going on.

![trello-ssb](https://cloud.githubusercontent.com/assets/981686/10675241/faae813a-78b3-11e5-988d-09986aa99dab.gif)

I feel like this is fundamentally related to a performance issue. There has to be something to the fact that I can run Trello in native Chrome and CPU usage between primary task & helper task is ~21/20% with no visible glitches or repaints vs running the same exact page in an Epichrome app and the CPU usage between primary task & helper task is ~84/12%.

Some weird but relatively minor performance lag is happening when it's running in the wrapper that's exhibiting itself in an ugly way on complex pages run at this huge resolution.

**Anecdotal additions:**
* Performance issues don't seem to happen on the non-retina screens I have been able to test.
* The same glitchy "repaint" looking issues happen at normal retina resolution ("looks like" 1440x900) but they come in and out so quickly that it doesn't have a big impact on the usability of the page.   
* The glitchy issues are only really severe when I'm on a scaled retina resolution ("looks like" 1920x1200) with complex pages (like a Trello board with many cards)

**Comment by dmarmor** [comment]
Hmm. I have to confess, I'm at a loss. I really thought taking out that key would fix it. The only other thing I could think of to do would be to Get Info on your Trello app in the finder and check the "Open in Low Resolution" checkbox (assuming it's not already checked). If re-running the app after doing that still yields the same problem, then I don't know what else to try. Unfortunately, I just don't have the hardware to reproduce this bug.

If you have any other thoughts, I'm game to try messing with things, but this is a real head-scratcher, as Epichrome really isn't modifying Chrome in any way. Once an app is up and running, it should behave exactly like regular Chrome...

**Comment by editdude** [comment]
While I'm not a developer or programmer, I'm willing to help investigate this issue. I'm using Epichrome to create an SSB for Asana.com and I, too, am seeing the redraw flicker phenomenon.

![asanascreensnapz001](https://cloud.githubusercontent.com/assets/15342809/10758269/cf2fa13e-7c86-11e5-83d5-298705af9367.gif)

**Comment by mhwinkler** [comment]
Well, I'm glad to know it isn't just me! As an FYI - the suggestion that was made: 
``` Get Info on your Trello app in the finder and check the "Open in Low Resolution" checkbox ```

Seems to have fixed the issue for me, but it requires me to run the app in the sometimes difficult to read low-res mode. Contrast that with running the same page in Chrome which works at high res without the glitches. Wish

**Comment by editdude** [comment]
Well blow me down. Low Resolution mode is indeed a workaround. Ugh, so blurry, but it's better than the flickering.

**Comment by dmarmor** [comment]
Hey guys--I had a thought as to a test you could try that might at least help isolate where the problem is (I'm still not sure there'll be any way to fix it as long as I can't see it myself). The idea is to launch Chrome exactly as Epichrome does, but do it manually from the command line. Here's the command you'll want:

```bash
"<path-to-Chrome>/Contents/MacOS/Google Chrome" --user-data-dir="<full-path-to-epichrome-profile>" "<url-1>" "<url-2>" "<url-3>"
```

That will launch a separate instance of Chrome using the settings and extensions you have in your Epichrome app. The dock icon and menubar name will be Chrome, but otherwise it should function exactly like your app.

The --user-data-dir flag should point to wherever your profile for the Trello (or Asana) app is stored. It's very important that this is the *full path*, not a path with a ~ in it. If you get that path wrong, Chrome will try to create a new profile, probably in its default location.

Here's what the whole command would look like on my system:

```bash
"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --user-data-dir="/Users/dmarmor/Library/Application Support/Epichrome/Apps/Trello" "https://trello.com/b/XXXXXXXX/board1" "https://trello.com/b/XXXXXXXX/board2" "https://trello.com/b/XXXXXXXX/board3"
```

(Note--the quotes are important if any of your paths or URLs have spaces or special characters in them.)

Anyway, let me know what happens when you do that! I have no idea whether to expect that it'll be slow and glitchy or not...

**Comment by mhwinkler** [comment]
@dmarmor - I hope this helps track it down... Your suggestion completely fixes the issue for me! If I run it like this:
```
"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --user-data-dir="/Users/matt/Library/Application Support/Epichrome/Apps/Trello" "https://trello.com/b/xxxxx/yyyyyy" "https://trello.com/b/xxxxxx/yyyyyyy" "https://trello.com/b/xxxxxx/yyyyyyy"
```

And the repaint/performance issue is gone. It performs exactly like it does in Chrome at retina display quality. The repaint/performance issue is still there when I launch my Trello.app made via Epichrome (unless I launch it in low-res mode).

**Comment by dmarmor** [comment]
OK, that's interesting. So it might just be the fact that it's wrapped in a different app that's causing the problem. So here are a couple more tests to try. The first and simpler test is to run from the commad-line again, but instead of calling the Chrome executable directly, we'll call the symlink inside your Trello app. The only thing you need to change is the path to Chrome at the start. The command will look like this:

```bash
"<path-to-your-Trello-app>/Contents/MacOS/Chrome" --user-data-dir="/Users/matt/Library/Application Support/Epichrome/Apps/Trello" "https://trello.com/b/xxxxx/yyyyyy" "https://trello.com/b/xxxxxx/yyyyyyy" "https://trello.com/b/xxxxxx/yyyyyyy"
```

If the issue is still gone when run that way, then the next thing to do would be to create a minimal app wrapper that does nothing but exec that command-line. Here's how you can try that:

1. Compress your Trello app into a zip or tgz file to save the full version as a backup.
2. Use your favorite text editor to edit this file:

```bash
<path-to-your-Trello-app>/Contents/MacOS/Epichrome
```

Replace *all* my gobbledygook in that file with this script (aside from the opening shebang, it's the exact same command as above):

```bash
#!/bin/sh

"<path-to-your-Trello-app>/Contents/MacOS/Chrome" --user-data-dir="/Users/matt/Library/Application Support/Epichrome/Apps/Trello" "https://trello.com/b/xxxxx/yyyyyy" "https://trello.com/b/xxxxxx/yyyyyyy" "https://trello.com/b/xxxxxx/yyyyyyy"
```

Close it out and run the Trello app.

And let me know what happens! Still not sure if I'll be able to fix this, but maybe we can at least isolate what's causing it.

Thanks!

**Comment by mhwinkler** [comment]
@dmarmor I appreciate your dedication to the cause here...

So far, running the Epichrome app from Terminal as you suggested causes the repaint / glitchy issue to occur the same as it does when I double click my Trello.app.

Debugging output below:
```
"/Applications/Trello.app/Contents/MacOS/Chrome" --user-data-dir="/Users/matt/Library/Application Support/Epichrome/Apps/Trello" "https://trello.com/b/xxxxxx/yyyyyyy" "https://trello.com/b/xxxxxx/yyyyyyy" "https://trello.com/b/xxxxxx/yyyyyyy"
2015-11-11 19:31:38.297 Chrome[38048:15232861] NSWindow warning: adding an unknown subview: <FullSizeContentView: 0x7f92b8596b50>. Break on NSLog to debug.
2015-11-11 19:31:38.298 Chrome[38048:15232861] Call stack:
(
	0   AppKit                              0x00007fff9d283807 -[NSThemeFrame addSubview:] + 107
	1   AppKit                              0x00007fff9d28354c -[NSView addSubview:positioned:relativeTo:] + 211
	2   Google Chrome Framework             0x0000000104379a23 ChromeMain + 51042723
	3   Google Chrome Framework             0x000000010437887c ChromeMain + 51038204
	4   Google Chrome Framework             0x00000001043e6171 ChromeMain + 51486961
	5   Google Chrome Framework             0x000000010433617c ChromeMain + 50766076
	6   Google Chrome Framework             0x00000001043421b2 ChromeMain + 50815282
	7   Google Chrome Framework             0x0000000104450cbc ChromeMain + 51924028
	8   Google Chrome Framework             0x000000010448567a ChromeMain + 52139514
	9   Google Chrome Framework             0x0000000104484802 ChromeMain + 52135810
	10  Google Chrome Framework             0x000000010448436d ChromeMain + 52134637
	11  Google Chrome Framework             0x00000001044839e3 ChromeMain + 52132195
	12  Google Chrome Framework             0x000000010448353d ChromeMain + 52131005
	13  Google Chrome Framework             0x00000001044815cf ChromeMain + 52122959
	14  Google Chrome Framework             0x00000001044811df ChromeMain + 52121951
	15  Google Chrome Framework             0x00000001044807c1 ChromeMain + 52119361
	16  Google Chrome Framework             0x000000010136b697 ChromeMain + 652823
	17  Google Chrome Framework             0x000000010136a5ba ChromeMain + 648506
	18  Google Chrome Framework             0x00000001046c6b0a ChromeMain + 54504074
	19  Google Chrome Framework             0x0000000104965e97 ChromeMain + 57253399
	20  Google Chrome Framework             0x00000001046c50bd ChromeMain + 54497341
	21  Google Chrome Framework             0x00000001046c9005 ChromeMain + 54513541
	22  Google Chrome Framework             0x00000001046c2daf ChromeMain + 54488367
	23  Google Chrome Framework             0x00000001018817bc ChromeMain + 5986108
	24  Google Chrome Framework             0x0000000101880e16 ChromeMain + 5983638
	25  Google Chrome Framework             0x00000001012cc0c2 ChromeMain + 66
	26  Chrome                              0x00000001012bff39 main + 9
	27  Chrome                              0x00000001012bff24 Chrome + 3876
)
[1111/193138:ERROR:mach_broker_mac.mm(52)] bootstrap_look_up: Unknown service name (1102)
[1111/193138:ERROR:browser_io_surface_manager_mac.cc(47)] bootstrap_look_up: Unknown service name (1102)
[1111/193138:ERROR:mach_broker_mac.mm(52)] bootstrap_look_up: Unknown service name (1102)
[1111/193138:ERROR:browser_io_surface_manager_mac.cc(47)] bootstrap_look_up: Unknown service name (1102)
[1111/193138:ERROR:mach_broker_mac.mm(52)] bootstrap_look_up: Unknown service name (1102)
[1111/193138:ERROR:browser_io_surface_manager_mac.cc(47)] bootstrap_look_up: Unknown service name (1102)
[1111/193138:ERROR:mach_broker_mac.mm(52)] bootstrap_look_up: Unknown service name (1102)
[1111/193138:ERROR:browser_io_surface_manager_mac.cc(47)] bootstrap_look_up: Unknown service name (1102)
[1111/193138:ERROR:mach_broker_mac.mm(52)] bootstrap_look_up: Unknown service name (1102)
[1111/193138:ERROR:browser_io_surface_manager_mac.cc(47)] bootstrap_look_up: Unknown service name (1102)
[1111/193139:ERROR:mach_broker_mac.mm(52)] bootstrap_look_up: Unknown service name (1102)
[1111/193139:ERROR:browser_io_surface_manager_mac.cc(47)] bootstrap_look_up: Unknown service name (1102)
[1111/193139:ERROR:mach_broker_mac.mm(52)] bootstrap_look_up: Unknown service name (1102)
[1111/193139:ERROR:browser_io_surface_manager_mac.cc(47)] bootstrap_look_up: Unknown service name (1102)
[1111/193139:ERROR:mach_broker_mac.mm(52)] bootstrap_look_up: Unknown service name (1102)
[1111/193139:ERROR:browser_io_surface_manager_mac.cc(47)] bootstrap_look_up: Unknown service name (1102)
```

**Comment by dmarmor** [comment]
OK, that's good information! Ready to try experiment 3? If this one works, it could point to a possible solution (though it's not completely ideal, as you'll see).

This is a more complicated procedure than the previous things we've tried. We're going to re-package your Trello app. The way Epichrome currently works, it uses a link to Chrome, so each Epichrome app is very small (about 2.5MB). But our previous experiments seem to indicate that trying to run Chrome from that link may be what's causing your problem.

So what we're going to do now is hand-build an Epichrome app *inside a copy of Chrome* instead. It's a bit of an involved procedure, and you need to be careful with each step, or you could end up with an app that won't run. So here goes:

*[Note: In these steps I'm going to use the abbreviation* ***\<old-trello\>*** *to indicate the full path to your original Trello Epichrome app, and* ***\<new-trello\>*** *for the path to the new one we're creating.]*

**Step 1**: Before we start, I'd suggest making a zip of your original Trello app so you have a backup in case anything happens to the original.

**Step 2**: We need a copy of Chrome to colonize with the new Trello app. You'll need to copy "Google Chrome.app" from wherever it is on your system and rename it to have the same name as your current Trello app. I'd suggest renaming your original Trello app to some temporary name without the .app extension, then copying Chrome and renaming it in the same folder. It would look something like this:

```bash
cd /Applications
mv Trello.app TrelloOld
cp -a "Google Chrome.app" "Trello.app"
```

(From here forward, <old-trello> will refer to the path to the renamed original Trello app, and <new-trello> will refer to the path to the new one we just created.)

**Step 3**: First thing we need to do is replace the Info.plist file:

```bash
rm "<new-trello>/Contents/Info.plist"
cp "<old-trello>/Contents/Info.plist" "<new-trello>/Contents"
```

**Step 4**: Now we need to create an Epichrome executable script.

```bash
touch "<new-trello>/Contents/MacOS/Epichrome"
chmod 755 "<new-trello>/Contents/MacOS/Epichrome"
```

**Step 5**: Now we'll populate the Epichrome script. We'll be using a simple stub script just for proof of concept, so it'll have to be hardwired with the *full path* to the new Trello app (you can't move the app after this, or it'll stop working). Open the newly-created Epichrome file in your favorite editor and enter this (of course replacing the URLs with the real ones):

```bash
#!/bin/sh

exec  "<new-trello>/Contents/MacOS/Google Chrome" --user-data-dir="/Users/matt/Library/Application Support/Epichrome/Apps/Trello" "https://trello.com/b/xxxxx/yyyyyy" "https://trello.com/b/xxxxxx/yyyyyyy" "https://trello.com/b/xxxxxx/yyyyyyy"
```

**Step 6**: Next, we need to replace the localization directories and the app icon with the Epichrome ones (note that with the first two commands, you may need to escape any spaces in the pathname, since you can't quote the wildcard):

```bash
rm -rf <new-trello>/Contents/Resources/*.lproj
cp -a <old-trello>/Contents/Resources/*.lproj "<new-trello>/Contents/Resources"
rm "<new-trello>/Contents/Resources/app.icns"
cp "<old-trello>/Contents/Resources/app.icns" "<new-trello>/Contents/Resources"
```

**Step 7**: Run <new-trello> in high-res mode and cross your fingers!

**Step 8**: When you're done, either delete or rename the experimental Trello app to something without a .app extension, and rename your original back so the system can find it again.

Sorry it's such a long, annoying process. If anything is unclear, please let me know and I'll try to clarify. The good news is, if this solves the problem, then I should be able to incorporate it as an option into the next version of Epichrome.

Anyway, let me know how it goes!

**Comment by mhwinkler** [comment]
Ok - I followed the directions step-by-step, but when I launch the new Trello.app by double clicking it, it just launches a new Chrome window (not a new application, it says Chrome and it's tied to the same instance/icon as my normal Chrome window). I think it's because the Application is still directly launching from `Trello.app/Contents/MacOS/Google Chrome`

**However, good news!** I can get the Trello.app running (with icon and isolated instance like normal), free of the aforementioned repaint/CPU performance issues, if I launch the new Trello.app using the following command:
```
exec "/<new-trello>/Contents/MacOS/Epichrome"
```

So awesome! Thank you for helping get to the bottom of this. Let me know if I can be of any assistance getting a fix ready for the next release.

**Comment by dmarmor** [comment]
Hmm. That's puzzling, since the command that worked for you is supposed to be exactly what double-clicking the app executes. Do you still have the experimental app? Can you double-check that you copied the Info.plist from the original app into the new one? The Info.plist file should have the following key in it (toward the end of the file):

```xml
	<key>CFBundleExecutable</key>
	<string>Epichrome</string>
```

**Comment by mhwinkler** [comment]
Yeah, something is funky, my Info.plist definitely has that line but it clearly is ignoring it for some reason.

On the positive side, when the app is launched manually via that Epichrome script it seems to run beautifully.

**Comment by dmarmor** [comment]
Well, it seems we have a solution, then. I'm still a little troubled by the fact you can't launch your experimental app normally. I just re-ran the experiment myself to confirm that when I double-click I get a separate dock instance from Chrome and the menubar name is correct.

Before I declare this a solution, would you mind making a couple last checks to see if we can get you to be able to actually launch your experimental Trello app by double-click and have it work correctly? I'd feel a lot better about diving into the changes knowing it was 100% working on a retina system.

The two main things I can think of to check would be to make sure the name of the Epichrome executable script and its permissions are exactly correct. Any problem with either might make it not launch properly. The name is case-sensitive, so needs to have the capital E. My guess is you've already checked both spelling and permissions, but wanted to double-check.

The only other thing I can think of is that somehow OSX hasn't grokked to the change in the Info.plist file somehow. I've found that sometimes when I've mucked around inside an app, I need to drag it to a different folder in the Finder, then drag it back. That causes the icon to update and things like that. Alternatively, if you use the terminal to rename the .app folder something without a .app extension, then rename it back, that usually tells the system to update it.

Anyway, if you wouldn't mind trying those things and just report back to me if it's working or not?

Once we've got it working so you can launch the app normally, I'll feel very good about moving forward with this solution.

**Comment by mhwinkler** [comment]
How very odd - a reboot didn't clear it out but as you suggested, moving the Trello.app into another folder using Finder and then moving it back caused the changed .plist to get picked up. Now the app launches successfully upon double-clicking. 

Better yet, it performs on-par with the native Chrome experience. No more low-res mode hack needed. So great!

**Comment by dmarmor** [comment]
Woo hoo! Solved. I'll add it to my to-do list for the next version of Epichrome. In the meantime, you can probably continue using the experimental version as long as you don't move it--though it will not auto-update when Chrome updates itself, so you might need to occasionally recopy Chrome and inject all the Epichrome stuff back into it by hand.

I'll make this a priority item since it's a usability issue and will keep you posted on it. For now, I'll close the issue.

Thank you for all your help tracking it down! I really appreciate all the testing you did.

**Comment by mhwinkler** [comment]
Just wanted to provide some follow-up information. When I launch the newly created SSB this way, it doesn't appear to store any user data. For example, if I sign in to Gmail with a new account, quit the app, and then re-open it, Gmail opens up as if I was logging in for the first time. 

This only appears to be the case if I perform the steps above with a fresh SSB. If I used the original SSB to log into all of my services before swapping it over, then the user data seems to be available from that previous usage. The `--user-data-dir` does exist and is pointing to the correct Epichrome user data directory.

**Comment by dmarmor** [comment]
Just wanted to give you a heads-up that I got this and am checking it out. I'm out of town and won't be able to look into it for a week or so, but I'll look into it as soon as I can and see if there's a way to solve it...

**Comment by dcasegr** [comment]
I just wanted to contribute that I'm see the same screen redraw issues on a 5K iMac.

**Comment by dmarmor** [comment]
Just a heads-up I haven't forgotten about this. I've hit a dilemma where fixing it seems to break Chrome's web credentials system (e.g. @mhwinkler's comment from 11/23/15). I also don't have much time to spend on this these days, but when I can I keep poking at it. Hoping I'll figure something out soon...

**Comment by dmarmor** [comment]
Another update: I believe I've figured out how to solve it! It's kind of a hairy change, though, so might take me a while to have time to implement it. But we will get this fixed in the next version.

**Comment by jdsimcoe** [comment]
Sweet!

**Comment by breeden** [comment]
Excellente!

**Comment by dmarmor** [comment]
OK, everyone. New release 2.1.8 is up. I believe it fixes this bug without causing the weird credentialing problem me and @mhwinkler were experiencing a couple months ago. Check out the release, and let me know how it goes. Thanks!

**Comment by dmarmor** [comment]
Anybody try this yet? Hopefully this should fix the retina performance problems and the WebGL problem.

I have noticed that on my system, the first time I run an updated app, it shows the wrong icon in the task switcher, but if I quit and run it again, it works perfectly.

**Comment by dcasegr** [comment]
From limited use today, it does appear to have cleaned up the redraw issues I was seeing. 

Thanks so much!.

**Comment by editdude** [comment]
I just updated and made sure to uncheck the "low resolution" box in Get Info. With just an initial mousing around, it appears to be solved for me. Thanks a BUNCH for the update. I'll chime in if I notice any additional repainting with future use of the SSB.

**Comment by dmarmor** [comment]
Great to hear! Thanks for checking in & yes, definitely let me know if any problems crop up.

**Comment by mhwinkler** [comment]
Delayed chime in here to say it appears to have resolved the issue for me as well. HUGE THNKS to @dmarmor for this update. I can finally switch back to using my favorite SSB app.

**Comment by dmarmor** [comment]
Thanks, @mhwinkler, glad it's back in action for you.
