### ISSUE TITLE
how to clone SSB apps?

### ISSUE THREAD

**Issue by gregschroeder** [dmarmor/epichrome#312]
Over the years, there have been periodic discussions here on how to clone a created SSB app.  Several techniques have been discussed, but I'm not sure which (if any) remain valid today, so I want to ask with the latest state of Epichrome and its browsers in mind.

There are a couple of main use cases for wanting this:
1. Copy an SSB to another computer
2. Use as a template for a new SSB

I have both of these needs, quite regularly.  Ideally, I would like absolutely everything copied - browser settings, bookmarks, passwords, installed extensions, etc.  (History is not important.) Manually going through all of these steps is a bit tedious and error prone.

Previously, there was talk about how one could check SSBs into Git.  Is this still true, and if so, which parts?  Just the app folder?  Symlinked payload folder?  App support folder?  etc.   

I am under the impression that use case (1) is harder because of the encryption used being tied to the original computer, but perhaps not.

I have switched to using internal Brave over external Chrome - the collision issues and other problems outweighed the benefits of still having 1Password support, etc.  So, this means I should be able to use Brave sync for (1), but that isn't at all what I want for (2).  For that, I want a common base but not identical copies thereafter.  I guess I could set up sync and then disable it after the initial copy.  Hmm..

For (2), I currently use a shell script (updated for 2.4.x changes) to create SSBs from the command line, but that just automates the same stuff that the wizard dialogs would in Epichrome, stopping well short of bookmarks, extensions, passwords, etc.  If I knew what (and how) to copy a 'base', the shell script could first do the copying, and then run an 'edit'/'update' command (as opposed to 'build') to change the name, start page, icon, etc.

Can you offer your advice on how best to achieve copying-to-other-computer and cloning-as-template?  Ideally, it would be a way that could be scripted.  If that could be a common mechanism, great, but if not, also fine.  

Thanks!

**Comment by dmarmor** [comment]
So copying an Epichrome app to another computer should be straightforward. The steps would be:

1. Make sure the app isn't running.
1. Zip or tar the app.
1. Copy to the new computer (which must have Epichrome installed).
1. Unzip and run.

It would then run as a new app, creating a new data directory. There's not a great way to transport browser settings between computers due to Chromium security and encryption, so likely if you tried to copy a data directory, you'd get a bunch of problems with corrupted settings and your extensions wouldn't make the journey. There's nothing I can do about that.

For the case of using an app as a template for another, that can be done, but it's a bit more delicate and I can't guarantee how well it would work. You'd want to do something like this:

1. Zip up *both* the original app and its data directory. You can leave both in their original enclosing folders.
1. Open the app for editing in Epichrome and change whatever settings you want.
1. On the confirmation page, click the `Advanced Settings` button and either enter a custom ID or click the `Create Default` button to let Epichrome do it for you.
1. Continue past the update advanced setting and save the changes.
1. The app should now be transformed into the new clone with its own ID, and its data directory will have been automatically moved to the new ID as well.
1. Now unzip both the original app and the original data directory.

Now you should have both apps with their own forked versions of the same data. I can't guarantee there won't be some weird collision problem with the Chrome/Brave user data directory, because there's a *lot* of strange stuff in there I don't understand. But I suspect it'll work.

In order to script this, you'd have to replace the steps that involve running Epichrome to edit the app with a call to `epichrome.sh` that sets all the correct values. If you have trouble with that, let me know and I can try to point you in the right direction.

As for checking an app into Git, I don't recall discussing that, but it should be technically possible. You'd just need to make sure you did it only when the app was not running, and I think you'd need to check the entire app bundle in. I suppose you could also check the data directory in, but as above I strongly doubt it would work well if you then cloned the repo onto a different computer. But the Git method could take the place of doing a bunch of zipping and unzipping if you were cloning apps on the same computer.

**Comment by gregschroeder** [comment]
Thanks for the update.

For copying to another computer, I will use your suggested technique and then apply Brave Sync to get the rest.

For creating from a template, I've created a script to do as you suggested.  So far, it seems to work well.  One very minor issue is that the Epichrome-created bookmark folder for the app history of changes didn't get updated, so it is still the old name.  This will likely cause issues in subsequent updates.  In that folder, the link to the previous revision also now fails.

Thanks again for the useful input.

**Comment by dmarmor** [comment]
I don't believe the name of the folder should prevent future welcome messages from being archived there (it's been a while, but I think I use a folder ID for that). But as for old links not working, that is correct. There's no automatic way to update those old bookmarks, as they assume the path to the welcome HTML file will not change, which it of course does if you clone an app to a new ID. You could go into the bookmark manager by hand and update their URLs to the new path. But honestly, opening those old bookmarks is mostly pointless as the actual welcome file is just the one from the latest version anyway. My intention with those bookmarks is really to be able to pop open the menu and see a log of updates and edits to the app.
