### ISSUE TITLE
How to disable the welcome screen?

### ISSUE THREAD

**Issue by chr0max** [dmarmor/epichrome#323]
Hi, 

the welcome comes after every update, is there a way to disable it?

Thanks.

**Comment by chr0max** [comment]
Is there no way?

**Comment by talleux** [comment]
I'm interested too ;)

**Comment by chr0max** [comment]
Oh cool, thanks!

**Comment by dmarmor** [comment]
This has been added to version 2.4.5, which will be up later today. It's an advanced setting, so if you're creating or editing an app, continue through the settings until you get to the summary dialog. That will have an `Advanced Settings` button. Click that and go through the advanced settings until you get to the last one, which will ask about skipping the welcome page. Answer Yes to that, and you should be set. Epichrome will remember your last choice for this setting and use it as the default for creating new apps.

Please give it a try and let me know how it goes. If all is well, we can close this issue. Thanks!

**Comment by talleux** [comment]
Thanks @dmarmor !
Is there a way to change this setting on all apps on a faster way than going through the edit wizard on each app? Like editing a config file? I know it's insane to have now about 50 apps... but if i could do a batch edit of a config file, this would be easier. Never mind, otherwise i can change it one by one occasionally

**Comment by chr0max** [comment]
Thats exactly the first thing in my mind. A way of editing multiple ones in one settings window (without going through the wizard) will have to come at some point.
