### ISSUE TITLE
Feature request: using Epichrome with Chromium

### ISSUE THREAD

**Issue by tersenius** [dmarmor/epichrome#33]
Hello,

thanks for this great project!

I'm using Chromium as default browser on my Mac. It would be great if I could be using Epichrome together with Chromium and not only Chrome. I've tried using a symlink or an alias as workaround, but this didn't work unfortunately.

Cheers
Ronald

**Comment by dmarmor** [comment]
Hi @tersenius,

I've never used Chromium, so don't know if or how that would work as an engine for Epichrome. Does it install as a separate app on your system along with Chrome, or is it a replacement?

As written, Epichrome will *only* use Chrome as its engine--it's keyed specifically to Chrome's app ID. It'd require some rewriting to support Chromium and I'm not sure whether it would work at all. It'd depend on how similarly it works to Chrome and how compatible their command-line interfaces are...

**Comment by tersenius** [comment]
Hi #dmarmor,

thanks for getting back to this so quickly. Chromium is the open source variant of Google Chrome. It's based on the same sources, just some rather Google-specific features might be different. Extensions work the same in both. So CLI- and API-wise it should not be a big issue.

Here you can find a comparison of both variants:
https://chromium.googlesource.com/chromium/src/+/master/docs/chromium_browser_vs_google_chrome.md

**Comment by dmarmor** [comment]
OK, it looks like it would likely work. I'll add it to my to-do list to test it out and add support for that. Just a heads-up, though--it may take some time for me to get to it, since I'm not making any more changes to the standalone Epichrome app. My next major update is going to involve switching it so Epichrome itself is a Chrome plug-in, and when I do that, if it's possible I'll add support for Chromium.

Till then, I'll close the issue...

**Comment by leogama** [comment]
Hi! I've reached this same issue today and the solution seems to be really simple – at least it worked for me. I just had to change the browser default path to "**/Applications/Chromium.app**", the executable to "**Contents/MacOS/Chromium**" and the identifier to "**org.chromium.Chromium**" in the `chromeinfo` function on [runtime.sh](https://github.com/dmarmor/epichrome/blob/master/app/src/runtime.sh#L495).

**Comment by dmarmor** [comment]
Yes, @leogama, your solution should work just fine. I *think* I wrote the code properly so those paths and identifiers only appears once in the code. Anyway, if it's working at all, then it's probably all good.

It's still on my to-do list to integrate Chromium in a nicer way, but that won't likely happen anytime soon, so this is a good solution till then.

**Comment by tersenius** [comment]
This has worked very well for me, thanks @leogama for sharing your solution!

**Comment by foliovision** [comment]
Thanks Leogama for the solution. I've tried applying it but still ended up with the error message:

> Creation failed: Unable to create icon (Unable to find Google Chrome executable.

![epichrome-unable-to-find-google-chrome-executable](https://user-images.githubusercontent.com/1180948/44453146-aac04580-a5f8-11e8-9592-c49bf169584e.png)

I'm attaching my runtime.sh. Perhaps someone could let me know which Chromium change I missed (I did hit all three of them. It could be that I don't keep Chromium in  "**/Applications/Chromium.app**" but instead in a folder "**/Applications/FVapps/Internet/Chromium.app**". "/**Applications**" is just too crowded.

[runtime.sh.zip](https://github.com/dmarmor/epichrome/files/2309520/runtime.sh.zip)

I'm really missing working SSB (long time Fluid user). I'd be happy to donate $50 to add Chromium functionality with choice of location for Chromium to the main app so more users who care about privacy could use Epichrome. It might make more sense to focus on Chromium as the main target:

1. the people who'd use SSB would be more than capable of installing Chromium
2. Chromium is easier to set up to protect user privacy
3. Chromium gets fewer breaking changes than main Chrome (where Google does whatever they want all the time, breaking whatever they want).
4. Chromium won't automatically update itself like Chrome breaking all SSB, creating pointless crisis and makework projects for SSB/Epichrome users.
5. breaking security fixes are usually less of a big deal for SSB (as SSB target specific SAAS sites which really shouldn't be trying to compromise the users' browser: you've got a problem with vendor choice if they do).

In the meantime, I'd be delighted just to get a working `runtime.sh` and some tips on what I did wrong so that others following here will be able to successfully use Epichrome with Chromium.

**Comment by dmarmor** [comment]
Hi @foliovision. Unfortunately, Epichrome's assumption of Chrome as its engine is such that I doubt changing runtime.sh in Epichrome itself will do the trick. You'll need to change it in the SSB itself after you've created it. Not ideal, especially if you're creating a lot of SSBs, but I suspect that's the only way to make it work until I have time to add proper Chromium support...

**Comment by foliovision** [comment]
Any hope of proper Chromium support as Google respect for privacy continues to detiorate and detiorate?

**Comment by dmarmor** [comment]
I'd like to do a little poll of folks who are interested in Chromium support. In which of the following ways do you think it should work?

1. If Chromium is installed, it is always chosen as the engine for Epichrome apps, whether Chrome is also installed or not. Only if Chromium is not installed is Chrome used as the engine.

or

2. If only one or the other of Chromium or Chrome is installed, then Epichrome apps are built using the installed one as their engine. If both are installed, then Epichrome asks which should be used as the engine for the newly-created app. In this way, a system could have some Epichrome apps that use Chrome and others that use Chromium.

(In either case, if one or the other was deleted later down the road, apps would probably automatically fall back to using the other as their engine.)

**Comment by foliovision** [comment]
Dmarmor, that's a great question. I'd like Epichrome to allow either (I'd only use Chromium as I won't allow Chrome on my computers), including the de-Googlized Chromium. Allowing Chromium may require adding a bit more code to Epichrome and/or removing a feature or two (if Google reserves SSB technology for Chrome as they often do to choke out Chromium adoption).

If either browser will work then it's as simple as the user choosing his preferred browser with automated reversion to the other in case the original is removed. That would be fanastic and resilient. I have a bounty for this available if it will help. I would be delighted to contribute $100 to Epichrome which would work well with Chromium on Mac.

**Comment by dmarmor** [comment]
Hi all. First off, I want to thank everyone who has requested I look into adding the ability to use Chromium as the app engine. In response to this feature request, I started experimenting with Chromium, and it turns out to have a number of major advantages over using Chrome as the engine.

Because of that, I'm now working on a relatively major update of Epichrome that would actually make Chromium the _default_ app engine. I do have a question about this, however. My feeling is that most users won't have the wherewithal to install their own builds of Chromium (which as everyone here probably knows, is not super user-friendly), so my intention is to actually bundle the Marmaduke build with Widevine and Google API compatibility with Epichrome and use that as the engine. I believe this will give most users the most seamless experience that's closest to the old Google Chrome engine.

As far as I can tell, the main potential downside of this setup would be that I will need to keep releasing new minor updates of Epichrome to keep up with new Chromium builds, and so users wouldn't be able to have the latest (or their chosen) Chromium build as the engine--they'll need to use the version bundled with Epichrome.

So here's my question: _For those of you who have been asking for a Chromium engine, would this be a good and useable setup for you?_

One last thing before I go:

#### <shameless_plug>
#### I've set up a [Patreon](https://www.patreon.com/epichrome). If you find Epichrome useful and would like to help support its continued development, I've love it if you considered joining. Your membership would help cover the costs and time I put into the project. Membership is per-release, so you'd only be charged when I put out a new version with significant work in it (e.g., assuming I end up with the bundled-Chromium architecture, I would not consider bumping the Chromium build to be a new version).
#### </shameless_plug>

**Comment by foliovision** [comment]
Dmarmor, I'm thrilled to hear this may be coming to Chromium. I'm having to do handstands to get half working SSB via webkit now and they are not very good.

Most people get their binary of Chromium from https://chromium.woolyss.com/ so in an ideal world you'd make Epichrome a plugin for Chromium. If Epichrome requires more in order to _create_ SSB you could make us install the Epichrome version for installing SSB but allow us to use another Chromium as our main Chromium.

Or we could have the Epichrome version on board at the same time. Running two versions of Chromium is not a great idea though. Perhaps you could create a version of Chromium with a different name which only runs the SSB. That would be fine with me too, although it would mean configuring two sets of preferences (not always a bad thing).

**Comment by dmarmor** [comment]
Hi @foliovision!

Well, I can tell you Chromium will definitely be an engine option in the next version. I've got it working in an internal build. I'm still working on making everything as smooth and bulletproof as possible before I go to beta, so it may be a while (definitely after the holidays). And I am using one of the woolyss builds (the Marmaduke one with Google API compatibility and Widevine built in). It will be packaged inside Epichrome, so you won't need to have a separate Chromium on your system, but it also should not interfere in any way with any build you have installed regularly. The only thing that won't be possible is using your own custom build as the engine. That would create too many variables for me to make it a usable experience for most people.

**Comment by foliovision** [comment]
Hi @dmarmor ,

Having two Chromiums installed should not be an issue. That's great that it will be possible to have two versions on board. I wish you'd called your version something slightly different though for clarity. EpiChromium would be fine.

**Comment by dmarmor** [comment]
The Chromium engine in the new build is packaged in with Epichrome.app, and when app engines are created using it they have their own bundle ID, so there's no need to call it anything. It doesn't exist as an app on the end user's system. So you can have whatever version of Chromium you want installed as an app and the Epichrome engine won't interfere with it.
