### ISSUE TITLE
How to force recreating an app

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#340]
I still have disappearing custom icon on my apps (showing the chrome native icon, ony while the app is started). In order to fix this I use to edit the app and do _any_ change in its configuration for the app to be created again - then the icon issue is fixed - for a certain while or until the next update, not sure exactly when the problem occurs.
This is a bit annoying because i have to make at least one change on the app configuration, which i don't want.

@dmarmor is there a way (e.g. a command) to let epichrome create the app again without having to actually change any configuration?

BTW: Running the scan app doesn't help (no problem found).

Thanks!

**Comment by dmarmor** [comment]
Hi @talleux, there's not really a way to do this. My best suggestions would be to either change something minor (like register as browser), save the edit, then do it again and put that setting back the way you want it. Otherwise, you could replace the icon with the same icon that that would get it to save without any real changes.

Sorry there's not a way to just "refresh" an app with no changes...

**Comment by talleux** [comment]
@dmarmor that's the way i do it until now (editing and doin a small change) but as this happen quite often it takes some time. Was just a try, thanks for you help anyway!
