### ISSUE TITLE
Preventing Missing Extensions After Hardware Change

### ISSUE THREAD

**Issue by ylluminarious** [dmarmor/epichrome#341]
Hey @dmarmor,

I know you're not actively maintaining this project anymore, but was hoping you could help me out with an issue I'm having currently. Due to an unfortunate mistake, I've accidentally changed my hardware ID on my machine and it caused a lot of authentication-based info to reset. Among these were my Epichrome browser extensions.

As you know, whenever the hardware changes on macOS, Chrome's policy is to remove all extensions (sometimes including their settings). The good news is that I've backed up my apps so that I won't lose my settings data or which extensions I had installed. However, I'm not sure how exactly what to do now that I've backed them up...

I noticed [a thread here](https://github.com/dmarmor/epichrome/issues/229) from last year, where you said that preserving:

```
UserData/Default/Extensions
UserData/Default/Local Extension Settings
UserData/Default/databases
```

were important for extensions to retain their settings. Is there some sort of way I can restore all of my extensions' settings from these folders, after I launch each app? Better yet would be a way to prevent Chrome from removing the extensions in the first place, after a hardware change, but I doubt that's possible or will work into the longterm future.

Any advice you could offer in such a situation would be greatly appreciated 🙂

**Comment by dmarmor** [comment]
Hi @ylluminarious, I'm not sure it would work to try to restore extensions and setting by copying those folders back after each launch. The problem is that Chrome has some kind of cryptographic magic that it uses to protect that stuff. At some point in testing Epichrome I tried copying over app data from one machine to another along with an app and it didn't work. The app came over, but all the extensions were lost and I think even some of the Chrome preferences got reset.

You could do an experiment and try it and see if reinstalling the extensions causes their settings to pop back in, but I fear they wouldn't, and there's not really a way around Chrome's security if it thinks you're now on a different machine...

**Comment by dmarmor** [comment]
Glad to hear it wasn't as bad as it could've been! I guess Google made some concessions to folks upgrading their hardware, which is good...

**Comment by ylluminarious** [comment]
@dmarmor Agreed 😸 

As a side, apparently some of these settings for the extensions are stored under:

```
~/Library/Application Support/Epichrome/Apps/MyApp/UserData/Default/Local Extension Settings
```

You can also see some of the extension hash ID's in there, although for some reason not all of the extensions appear to be there. Just thought this was an important note for anyone else potentially facing the same issue...
