### ISSUE TITLE
Suddenly stopped working after Chrome update

### ISSUE THREAD

**Issue by evansthompson** [dmarmor/epichrome#35]
I'm on the Chrome Dev channel. During the most recent update (I think), I got the Epichrome message that Chrome had been updated and the SSB was going to update, and I clicked OK. After that, though, nothing happened. 

I tried recreating the SSBs, and I created a new SSB. I uninstalled (from home brew) and re-installed (from Github), deleted and re-installed Chrome (still Dev). 

This is all I've found in the Console:

11/11/15 3:52:24.508 PM com.apple.xpc.launchd[1]: (org.epichrome.app.Office365.358112[11703]) Service exited due to signal: Abort trap: 6

**Comment by evansthompson** [comment]
OK. So after I wrote that sentence about re-installing Dev, I decided to install Stable and see what happened. Stable works, so something in Dev broke it. I guess in a couple of releases, it'll unbreak it. I hope. :)

FYI, the offending Dev build is 48.0.2560.0.

**Comment by dmarmor** [comment]
Thanks for the heads-up--sounds like something in that version of Chrome didn't like Epichrome (or vice versa). Hopefully it'll be fixed by the time it goes production.

I use Epichrome myself heavily, so if a new production version breaks it, I should be able to push out a fix pretty quick. I'll keep an eye out...
