### ISSUE TITLE
WebGL Issue

### ISSUE THREAD

**Issue by jdsimcoe** [dmarmor/epichrome#43]
When trying to run https://www.figma.com/ in Epichrome I get this curious error:

<img width="532" alt="screen shot 2015-12-30 at 12 54 02 pm" src="https://cloud.githubusercontent.com/assets/275617/12057466/2da736b8-aef6-11e5-8247-278b3d330e12.png">

**Comment by jdsimcoe** [comment]
@dmarmor Any idea on this error?

**Comment by dmarmor** [comment]
I just set up an app with that URL, and I can't get the error to happen. It doesn't appear I can go anywhere on that site past the front page, though. Do you have a preview login or something? Or do you see the error on the front page?

**Comment by jdsimcoe** [comment]
@dmarmor The error is several steps in and I don't have a login I can share :( I might try to create a public link that will break for you though... let me see...

**Comment by dmarmor** [comment]
I also signed up for a preview on the site, but I have no idea how long before they'd give me a login...

**Comment by jdsimcoe** [comment]
Try this link @dmarmor https://www.figma.com/file/PzH5ygqRea7WN5EkxrL7HLum/Epichrome-Test

**Comment by dmarmor** [comment]
Thanks for this--I am getting the same error message on that page. I'll poke around and see if I can figure out what's going on...

**Comment by jdsimcoe** [comment]
Great!

**Comment by dmarmor** [comment]
Well, I've found at least part of the problem, though it doesn't look good for an easy solution. If I go to:

chrome://gpu/

In Chrome, most of the items under Graphics Feature Status show as "Hardware accelerated." If I go to the same page in an Epichrome app, they show as "Software only" and WebGL shows "Unavailable." In fact, on a closer look, the problem seems to be that the GPU process was unable to boot.

When I've got some time, I'll poke around with command-line options and see if I can get Epichrome apps to run the GPU process (I'm not sure why they wouldn't by default). May take me a while, as my day job is crazy at the moment, but I'll get to it as soon as I can.

(It's possible this is also related to issue #31, so the same solution might work for both issues.)

**Comment by dmarmor** [comment]
Hey there, I'm now pretty sure this is the same issue as #31, so closing this one. Check that issue for updates. Thanks!

**Comment by jdsimcoe** [comment]
@dmarmor This works beautifully! Well done.

**Comment by dmarmor** [comment]
Great, thanks @jdsimcoe! Glad it's working.
