### ISSUE TITLE
Feature Request: Hide window on close

### ISSUE THREAD

**Issue by rtgibbons** [dmarmor/epichrome#60]
Not sure how possible this - it'd be nice if when closing the window, it wouldn't try to actually close it and instead just hide it.

**Comment by dmarmor** [comment]
I know for sure this isn't possible if you use the close button at the top of the window. It's possible I could overload Cmd-W so instead of closing the window it hides it. But I'm not even sure about that.

Sadly, I don't have time to add new features at the moment, but I'll add it to my to-do list. Thanks for the idea!
