### ISSUE TITLE
Generated App launches a standard Chrome window on 2nd launch

### ISSUE THREAD

**Issue by NickTikhonov** [dmarmor/epichrome#64]
When I create Epichrome apps, they exhibit strange behaviour on second launch. The first time an app is launched it works as expected, however when the app window is closed (Cmd + W) and reopened - a standard browser window is displayed (e.g. with the chrome start screen). When the app is quit properly (Cmd + Q) and reopened, it works as expected. 

Is this an issue with configuration, e.g. can it be avoided with a particular setting?

**Comment by mank319** [comment]
I encountered the same problem. Since the behaviour occurs on window close events, I would like to point out that the problem also applies when you close the window by clicking the close button in the window decoration. Maybe, as a workaround, would it be possible to force the corresponding Chrome instance to quit completely when a window close event has been received?

**Comment by raypaw** [comment]
This extension resolved this issue for me: https://chrome.google.com/webstore/detail/new-tab-redirect/icpgjfneehieebagbmdbhnlpiopdcmna

**Comment by dmarmor** [comment]
This is expected behavior. Epichrome apps are just wrappers around Chrome, and Chrome always opens standard browser windows. There's no way to make it open an app-style window.

@mank319, I like the idea of trying to force Chrome to quit when the main window is closed (as an option in the extension of course--I'm sure some people wouldn't want that behavior). I'll add it to the to-do list, though my day job is killing me now, so I probably won't get around to new features in the near future...

**Comment by NickTikhonov** [comment]
@dmarmor - to better explain this issue:

The second time an app is opened, instead of loading the associated URL - a new *empty* chrome window appears, the start screen. I would expect the app to open the correct URL, as defined when the app was created. What do you think? cc @mank319

**Comment by dmarmor** [comment]
I think the problem is that in the scenario you outlines, the app is still running. If you close the window with Cmd-W, but leave the app running, then launching the app again simply signals Chrome to open a new window--which will always be a regular tabbed window, and possibly always a blank one.

I have it on my to-do list now to try to add a behavior where the extension will cause the app to quit if you close the main window, which I think would resolve your problem, yes? That way even if you hit Cmd-W, the entire app would quit, so when you launched again, it would launch properly with your chosen window.

**Comment by NickTikhonov** [comment]
@dmarmor that is exactly the problem I've had, and force-closing the app should lead to desired behavior on next launch :)

**Comment by leogama** [comment]
Hi! I just started using Epichrome and faced this same problem. As it is, the Epichrome app is just a wrapper for Chrome in its "app mode", so after the app window is closed there's no way to "relaunch" it. And, because of this, there's no reason to the application to keep running after all windows are closed!

I devised a solution (tried it and **worked well**) in this way: just before launching the app, the Epichrome's main shell script can start a _background_ applescript that will monitor the app. Once it detects that all the windows were closed, it will send a signal to the application to quit (and will exit too after that). That's all! :smile:

The applescript is _really_ simple. It's something like this:
```applescript
delay 10  -- give some time to the app open
repeat while application "MyEpichromeApp" is running
    tell application "MyEpichromeApp"
        if (count of windows) is 0 then
            quit
            exit repeat
        end if
    end tell
    delay 5  -- interval between checks
end repeat
```

**Comment by dmarmor** [comment]
Thanks, @leogama! I'll add that to my notes. I still think the more optimal solution will be to have the extension quit Chrome if possible, but if that fails, this will be an elegant workaround...

**Comment by mank319** [comment]
Alternatively you can easily automate the "force close" mechanism using [BetterTouchTool](https://www.boastr.net).
Simple create a rule as shown in the screenshot below for the corresponding apps:

<img width="753" alt="screen shot 2016-08-25 at 16 10 56" src="https://cloud.githubusercontent.com/assets/3366745/17978518/720ac7ac-6aee-11e6-89a8-8332b9c4190e.png">
