### ISSUE TITLE
Taïga not connected to extension

### ISSUE THREAD

**Issue by clekos** [dmarmor/epichrome#66]
The link : https://tree.taiga.io/

![capture d ecran 2016-06-01 a 22 33 26](https://cloud.githubusercontent.com/assets/5139008/15724912/98041aa4-2849-11e6-9233-76e2de917c90.png)

**Comment by dmarmor** [comment]
Sorry for the slow reply. Are you still having this problem? Have you tried creating Epichrome apps for different sites? In those cases does the extension connect properly? (I doubt the problem is Taiga specifically. The extension doesn't even know what site the SSB is set up for.)

**Comment by JeremyMorel** [comment]
Hi there.  I know that it's been some time since this conversation was initiated, but I wanted to say that I am having the same issue with an entirely different site.  The site will load in the background, and seems to function ok, but the widow (as shown in the screenshot provided by clekos on Jun 1), is a window which pops up above it, and is allowed to close.  This shows up with each launch of the created application.

**Comment by JeremyMorel** [comment]
I believe I have isolated the issue to a special character in the name of the application.  In my case, I got cute and added the "TM" symbol.  Removing that resolved the issue.  It looks like the user above might have the "ï" in Taïga.  This is probably not being escaped properly or something, somewhere along the chain.  I may dig a little at some point to investigate, but for me, I'm content for now to remove my symbol and stop complaining.  Thanks for the great work!

**Comment by clekos** [comment]
Hello everyone, I'm not having this problem anymore because I disabled the epichrome options plugin. The app is launching correctly since this :)

**Comment by ylluminarious** [comment]
@JeremyMorel I was having the same problem as well, due to an apostrophe in the app name. I guess Epichrome should be fixed to handle special characters in the name... an apostrophe isn't even really a special character in my opinion. It's just standard ASCII so you wouldn't think that it would cause any problems.

**Comment by dmarmor** [comment]
Hi all, I think I've fixed this one. Here's a beta that addresses it. Could you please give it a shot and let me know if it fixes the problem for you?

https://www.dropbox.com/s/edldp8711bl3tgh/epichrome-2.2.5b02.dmg?dl=1

**Comment by dmarmor** [comment]
Hi all, I think I've fixed this problem finally. Here's a beta release to give it a try if you want. Please report here if it helps (or if it doesn't). Thanks!

https://www.dropbox.com/s/48njsemeb583dth/epichrome-2.2.5b03.dmg?dl=1
