### ISSUE TITLE
Feature req: a way to migrate SSB's or quickly create clones

### ISSUE THREAD

**Issue by treyharris** [dmarmor/epichrome#68]
Lately I've had to use a number of new Macs and there doesn't seem to be a way to cleanly move an Epichrome SSB from one to the other.

I don't know if exporting an importable definition file (where fully-qualified locations of things can be modified and maybe the icon is serialized into the export), or having a command-line way to run Epichrome, or something else is the easiest way to handle it, but it seems like there are a number of ways.

**Comment by dmarmor** [comment]
Hey @treyharris--I'm a little confused, since I've copied Epichrome SSBs from one system to another and had no problems. All the info for the app is stored in its bundle, so once on the new system it should autopopulate a new user profile. Or if you wanted to copy your profile from ~/Library/Application Support/Epichrome/Apps/<AppID> that should work too, I think.

What happens when you move an app bundle? Or maybe I'm misunderstanding what you're trying to do?

Thanks!

**Comment by dmarmor** [comment]
Hey @treyharris, closing this issue for now, but if this problem is persisting for you, let me know and I'll reopen...
