### ISSUE TITLE
Can't remove location bar from new window spawned from within SSB

### ISSUE THREAD

**Issue by lianos** [dmarmor/epichrome#70]
When using the original SSB window for the Epichrome-wrapped web application, a right-click dropdown menu includes the Epichrome-specific option to "Show/Hide Address Bar".

New windows that are spawned from the main window open with a location bar and there's no option in the richt-click/context menu to toggle it away.

**Comment by dmarmor** [comment]
Currently, only the original window opened by an Epichrome app is considered to be the "app window" since Epichrome apps are meant to act as single-use apps. I'll put it on my to-do list to allow other windows to be spawned as "main" type windows, but I'm not sure how practical that will be given the way Chrome operates. I'll have to look into it. Thanks for the feedback!
