### ISSUE TITLE
Stuck with old version

### ISSUE THREAD

**Issue by zeartist** [dmarmor/epichrome#71]
I tried updating everything to the most recent versions, step by step, but it failed (my SSBs). Essentially, my current state:
- OSX: 10.8.5
- Chrome: Version 44.0.2403.107 (64-bit)
- MakeChromeSSB (old epichrome) 2.0.1

to (from memory, as of around June 12):
- Chrome 48 or 49'ish
- Epichrome 2.1.11

Tried updating just chrome, but then my SSBs won't work. Then tried updating to Epichrome, but my SSBs did not update to follow, so nothing worked at that point. Then tried to re-create them all from scratch, but the newly generated SSBs don't run (silently crash on start). Note that it from a locally built Epichrome (from the source, make'd, since the binary did not run due to old OSX). Now Chrome joined to party and started complaining they won't support my OSX version.

So anyway, I guess I'm overdue for an upgrade on many fronts. I tried Yosemite but really disliked so that is out of the question. I'll likely get a newer mac sometime this year tho. But any ideas on how I could at least get Epichrome generated SSBs working?  Is there a way I can have both Chrome versions installed to play around some ideas instead of always using Time Machine (perhaps under different users?). On Windows I used sandboxie for this, but on mac I haven't found an alternative yet. I'm a software dev, so don't hesitate on technical info.

**Comment by dmarmor** [comment]
Yeah, I don't think it's possible to update from MakeChromeSSB 2.0.1 to the latest Epichrome (the auto-update system wasn't that robust in that early version).

As for your current difficulties, I'm not sure what to tell you. I don't have an install of 10.8 on my system, so I have no way of testing it. If even Chrome isn't working, then Epichrome apps *definitely* won't work, since they're just wrappers that launch Chrome instances.

I'm afraid the proper solution might be reinstalling the older version of Chrome and continuing to use your old MakeChromeSSBs with it. I don't have any experience with sandboxing different versions of apps on OSX, so I can't really help you there.

I'll close the issue for now (because I don't think there's a solution really). But please keep me posted if you find a solution, as it might help other users too. Sorry I can't be more helpful!

**Comment by zeartist** [comment]
Would you perhaps have a suggestion on how I might debug / pinpoint what causes the newer version (Epichrome 2.1.11) to fail to produce a working SSB?  Perhaps there's a way to enable some debug info / more verbose features... I'm just curious why 2.0.1 worked but not 2.1.11, or perhaps it's due to a requirement in Chrome versions? Let me know, I have some spare time and might help debug this (I'm mostly new to Mac related development but a capable software dev, I think ;-)).

**Comment by dmarmor** [comment]
It may have to do with the Chrome version--I've never tested later versions of Epichrome with very old versions of Chrome, and it could well be that the internal structure of the Chrome app bundle has changed in some way. (I'm assuming you're trying to make Epichrome SSBs using the older version of Chrome that works on your older version OSX?)

The easiest way to debug the failure of an Epichrome SSB is to invoke it from the command line like so:

```bash
<path-to-ssb>/Contents/MacOS/Epichrome
```

That will print any error messages to the terminal. You can also edit the Epichrome script as well as Resources/Scripts/runtime.sh to add extra debugging messages (I'd suggest you create a zip of your SSB first to serve as a clean backup).

Good luck! Let me know what you find...
