### ISSUE TITLE
Creating Epichrome apps programmatically

### ISSUE THREAD

**Issue by wizonesolutions** [dmarmor/epichrome#73]
Hi! I've been automating my machine with Ansible lately, and it would be neat if I could automatically ensure that my Epichrome apps were created. I presume Epichrome is already running various scripts that I could perhaps run programmatically to achieve the same result. I'm not sure if this documented, but if it is, could you point me towards it or give me some quick tips on where to look? I can try to contribute some documentation in the Wiki or whatever.

**Comment by dmarmor** [comment]
Hey--I'm not sure I fully understand what you're asking. Are you looking for a way to create an Epichrome app from the command-line? If so, that is feasible, since the AppleScript app ends up just communicating with a script to create the actual app.

But it's not a very friendly command-line, since it's only meant to run internally. Where you'd want to look is in main.applescript and find the section where it runs chromeSSBScript (the script itself is called build.sh). That'll show you the basic arguments you need to give it. It ordinarily runs a few informational scripts beforehand to get path info and such, so you'd need to bake the right paths in yourself.

Question: any reason you couldn't have Ansible just copy the apps from a repository? Epichrome apps are meant to be able to just be copied from machine to machine and they should populate new settings directories automatically.

Hope that helps! I'll close the issue for now, but feel free to reopen and/or give me further info if you were looking for something else.

**Comment by wizonesolutions** [comment]
@dmarmor Oh, apps can be put in Git? That's a much easier solution. I thought there was something machine-specific. I'll try that, thanks!

**Comment by dmarmor** [comment]
My only concern about adding an Epichrome app to a Git repository would be that Epichrome apps make heavy use of symbolic links internally. From what I can tell, Git handles symlinks just fine, so it _should_ be OK, but you'd want to experiment a bit...

**Comment by wizonesolutions** [comment]
👍 worked just fine. It would be cool to be able to sync profiles, but not too worried about that. Most apps I use aren't that cumbersome to log into.

**Comment by dmarmor** [comment]
Excellent! Glad it's working. Syncing profiles may be a little weird given that I think Chrome does some weird stuff to the profile directory while it's running. But I have successfully copied profile directories from one system to another so it may be possible to add those to Git as well. Might be worth a try anyway. Epichrome profiles are stored in:

```bash
~user/Library/Application Support/Epichrome/Apps/<ssb-id>
```

The <ssb-id> is usually easy to figure out as it's based on the name you give the SSB.

Good luck!
