### ISSUE TITLE
Can I enable chrome extension in the created app

### ISSUE THREAD

**Issue by huangyg11** [dmarmor/epichrome#75]
When I am creating app, I want to enable some chrome app, can I select one from existing chrome extensions?

And after created, can I show extension button in the app or show extension functionality in the app menu?

**Comment by dmarmor** [comment]
Yes! Any Chrome app or extension you can enable in Chrome, you can enable in any Epichrome SSB. You would add it the same way you would in Chrome (I usually start from chrome://apps or chrome://extensions).

As far as extension buttons, if you mean the little icons that appear in the toolbar, those would only be visible if your Epichrome SSB is tab-style. If it's app-style, you'd need to hit Cmd-Shift-L to switch into tab mode in order to see the icon.

Hope that helps!
