### ISSUE TITLE
Creating an application with an icon fails

### ISSUE THREAD

**Issue by io41** [dmarmor/epichrome#76]
<img width="532" alt="screenshot 2016-07-25 08 13 07" src="https://cloud.githubusercontent.com/assets/121624/17093200/b0343f58-523f-11e6-8529-1b88cc19b7a3.png">

Clicking "Create" results in `Creation failed: Unable to create icon (unable to convert iconset to ICNS file`:

<img width="532" alt="screenshot 2016-07-25 08 12 58" src="https://cloud.githubusercontent.com/assets/121624/17093199/b01fbf88-523f-11e6-8b09-3baf83ea883e.png">

Edit:
Chrome Version 51.0.2704.103 (64-bit)
Epichrome version 2.1.11
OSX 10.11.5

Without an icon the app is created correctly.

**Comment by dmarmor** [comment]
Hi @io41,

Has this persisted for you? I've never encountered this problem. Is it possible it's specific to the PNG file you're using? If you are still experiencing it and don't mind sending me the PNG file, it could be helpful.

Thanks!

**Comment by freewind** [comment]
Me too. Most of images I use have this problem. I will upload some to here

![inoreader](https://cloud.githubusercontent.com/assets/333781/18812848/e5102dcc-8313-11e6-95df-1d426b972e6a.png)

![jian](https://cloud.githubusercontent.com/assets/333781/18812849/eb0d416a-8313-11e6-8f93-99d613ccde90.jpg)

**Comment by dmarmor** [comment]
Thanks for sending these, @freewind. I'll check them out and get back to you.

**Comment by dmarmor** [comment]
Hey guys, I looked into this and the problem is that my icon-conversion code can't handle images without alpha channels. I probably won't have time to rewrite the conversion code for a long time, but in the next version, I'll update the error-reporting to properly note when that's the problem with an image.

For now, your best bet would be to just add an alpha channel to those images (and convert the first one to full RGB). Most any image-processing software can do this (the built-in OSX command-line tools can't, which is why I can't easily fix this).

Sorry for the inconvenience, and thanks for pointing out the problem!

**Comment by dmarmor** [comment]
Hey guys. Just released [2.1.14](https://github.com/dmarmor/epichrome/releases/tag/v2.1.14) which addresses these problems creating icons. Both of the example files @freewind posted now work correctly. Less importantly, Epichrome now creates a custom document icon to go along with the custom app icon.

Please note, if you're running 2.1.13, you'll probably have trouble updating. There's a note linked in the 2.1.14 release to help work around the problem.

Thanks!
