### ISSUE TITLE
Opening general browser window with SSB open

### ISSUE THREAD

**Issue by sashaweiss** [dmarmor/epichrome#9]
Hi! I've created a whole bunch of SSBs using this tool, I love it.  Many thanks for building it.

The one thing that's been bugging me is that if I have an SSB open, say for Gmail, I can't afterwards open my regular Chrome app (the one that has all my bookmarks, extensions, etc.).  Clicking the icon to open Chrome from the dock just does nothing.  The only way I can open regular Chrome is to have it open before I open any SSB, which is frustrating because I'll be using my SSB for email and then want to google something and be able to take advantage of the extensions and bookmarks I have in the original browser.

Again, love the app.  I've been experimenting with workarounds, but haven't found anything great yet.  Thanks in advance for your help.

**Comment by dmarmor** [comment]
Hmm...it definitely should not be doing that. I saw that problem with SSBs created by some of the tools that were around before mine, but never with my program. Can you give me a bit more info? What version of MakeChromeSSB did you use to create the SSBs? What version of OSX are you running?

**Comment by sashaweiss** [comment]
You know, that might be right.  I had been trying out another utility earlier, I must have gotten them mixed up.  I wasn't able to reproduce that bug, anyway.

I did, however, notice some other things...the workaround I ended up using was to make a "browser tabs" SSB that had no default tabs, and synced it with my other accounts to import all the same details, since other SSBs launched just fine.  When I was trying to reproduce the launch bug, I tried making some SSBs using the MakeChromeSSB app and chose to do App Window style SSBs.  However, when I launched them, they unilaterally came out as browser tab style ones, regardless of the option I chose.  They also opened to the default Chrome launch page, even when I entered an address for the SSB tabs to open to.  This only happened after I had made the first browser style one, which was supposed to open blank...I wonder if it got stuck somehow?

Also, in both the browser and app style SSBs I made it looked like the pages it opened were low-resolution somehow.  Images and text were all slightly blurred and low-res, which was frustrating.

I'm using the most recent version of MakeChromeSSB, and I'm on OS X Yosemite with all the most recent updates.

Best,
Sasha

**Comment by dmarmor** [comment]
Glad at least one problem seems to be solved!

I tried making two apps in a row, just as you said--the first with browser tabs but no tabs specified, the second with an app window. Both came out as intended, so I'm not sure about that problem. Is it possible it was just the tabs that sometimes get opened on the first run of an SSB? On my system, I get all these annoying tabs announcing the installation of the various extensions I have synced with my Google account. Once I quit the new SSB and run it again, though, it just shows the proper app window. Not sure if that's what you're seeing, but it seems worth making sure.

As for the low-resolution problem: do you have a retina screen? If so, then that's a known problem and is already fixed in the next version, which I'm hoping to post tonight or tomorrow.

Thanks,
  Dave

**Comment by sashaweiss** [comment]
With regards to the tabs, I'm not sure what's up with it but the way my setup is now everything works as I need it, I'll try getting a new copy of the app and see if that clears it up. Thanks for checking it out.

With regards to the screen, yes I am on retina! I'll make sure to look for the new release.

Thanks for much for your help!

**Comment by dmarmor** [comment]
Great--glad it's basically working. New release is up now, so give it a try and let me know how it works! Thanks for the feedback.

Cheers,
  Dave
