### ISSUE TITLE
Have you considered making a Swift app?

### ISSUE THREAD

**Issue by henderea** [dmarmor/epichrome#94]
Have you considered converting this to Swift?  I think having the Cocoa and other frameworks available to you would allow you to make a better interface, without the limitations of AppleScript.  It would also make it easier to codesign the app if you don't do that already.  If I have time, I might work on a conversion of my own, and I would put it on github so you could help out.  I do have my own codesigning identity, so I would be able to codesign it under my name if/when I complete it.  If you get/have a codesigning identity, you could codesign it under your own name instead.

I'm not too sure you can make a chrome extension that can do the sort of stuff Epichrome currently does.  I think your best bet is a desktop application of some sort.  Swift seems to be the way of the future on macOS, so it would probably be your best option for a native app.

**Comment by dmarmor** [comment]
Hey @henderea,

I did consider Cocoa for Epichrome.app, but I think ultimately doing it as a Chrome extension will be an easier and more seamless solution for most users, as Chrome is required to be installed anyway in order to use it. The idea is not that the extension would replace what Epichrome does, but rather that you'd make your Epichrome apps directly from within Chrome. This has obvious advantages, such as that Epichrome could just capture the open tabs you have open and offer those as the URLs for the app. And also, it could easily harvest icons from the internet to offer as app icons.

I'm not sure Epichrome apps themselves would benefit that much from being written in Swift, since they're just wrappers--all they really do is update- and sanity-checking and then they exec an instance of Chrome.

(That said, my day job is pretty much slamming me, so I'm not planning on doing anything more than maintenance for the foreseeable future...)

Cheers!
