### ISSUE TITLE
Epichrome Packages?

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#95]
You know, Epichrome is a real savior when it comes to keeping web apps, histories, etc. all isolated.  I find myself using Epichrome more and more and more each week.  I have apps for Walmart, Amazon, project management, and a multitude of other services that need isolation.

I've found myself wanting to share these apps with my family and associates.  They're becoming envious seeing my quick access and searching of things.  Eg, I run specialized searches for Amazon, Walmart, etc. all in these isolated instances.

Is there a way that we can start packing up Epichrome apps into a bundle that can be "self sufficient?"  It would be fantastic if everything were embedded into the .app bundle and then perhaps even the config were yanked in there with everything except the password / personal info.  I suspect some symlinks from the home library could be set up so that the actual config is kept in the bundle and then is also accessible from the library config folder as well, but it would sure be useful because I'm to the point right now where i'm having to manually transfer the app and config on a fairly routine basis.  And in our home alone I have several computers to transfer between now...

Thoughts?

**Comment by dmarmor** [comment]
Hey @ylluminate,

If I'm understanding what you're proposing, it's sort of how I originally thought of Epichrome, but then I ended up splitting out the profiles and putting them in ~/Library so that Epichrome apps would function more like regular apps (i.e. you could install a single, say, Gmail.app on a system and have it used by multiple users).

I guess the best compromise would be to offer a build-time option to keep the profile inside the app instead of in the library. That does of course run the risk of breaking catastrophically if two users did decide to run the same instance at the same time, and I'm also not sure how you'd avoid passwords and personal info being transported along with everything else, since it's all just part of the Chrome profile folder. Thoughts on that?

Anyway, I'll add it to my (sadly ever-growing) to-do list!

**Comment by ylluminate** [comment]
Hmm, well that's my question:  How is the Chrome profile stored precisely?  I think symlinks could potentially be used depending on the way the profiles are organized...

**Comment by dmarmor** [comment]
The profile is stored in a directory inside ~/Library/Epichrome/Apps/<app-id>/ that the Epichrome app sort of auto-populates with some of its own stuff, but then after that it's a pure Chrome profile directory.

If you're looking for an interims solution and wanted to experiment with it, you could move that folder inside your Epichrome app package (I'd recommend putting it inside the Contents/Resources directory), and then symlink it back to its original location. Obviously, do all that while the app is not running.

Of course that doesn't really solve your problem, because when you package it up and send it to another system, you'll need to recreate that symlink on their system before they run the app, or the first time the app runs it'll just create a new profile.

I suppose you could also hard-code a little bit of script into the app that looked something like this:

```bash
if [[ ! -e "$myProfilePath" ]] ; then
  ln -s "<internal-profile-path>" "$myProfilePath"
fi
```

You'd want to put that in Contents/MacOS/Epichrome, just below where $myProfilePath gets defined.

Of course, it's a fragile solution, since it'd get blown away if the Epichrome app updates itself. But it could serve as a stopgap?
