### ISSUE TITLE
How reregister an Epichrome app?

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#99]
I'm having an issues where it appears that Browser Fairy is not recognizing one of my Epichrome apps.  Is there a shell incantation that will reset the app being recognized as a web browser by the system?

**Comment by dmarmor** [comment]
This is a toughie...I don't really know any way to force Browser Fairy to recognize an app that it's lost. Have you checked to see if the app it's not recognizing still appears in the list of browsers in System Preferences->General->Default web browser?

**Comment by ylluminate** [comment]
Some are and some aren't... Really seems peculiar.

**Comment by dmarmor** [comment]
I haven't seemed to be able to recreate this behavior. Unfortunately, I think the best bet right now would be to recreate any apps that are lost using the method in the readme so that you can keep your settings intact. Sorry about that. I am working (very slowly, as work doesn't leave me much time these days) to improve things so that apps will eventually be editable from within their helper extension.

**Comment by dmarmor** [comment]
Closing this issue for now. The next major update I think will clean up the Browser Fairy issue, but it'll be a while before it happens (day job isn't leaving me much time for Epichrome right now).
